-- =====================================================================
-- 0003_seed_organizations.sql  (Supabase Project 1)
-- Verified worldwide organization seed (~110). Careers URLs must be
-- individually confirmed before wiring a scrape_source to each (see docs).
-- =====================================================================

INSERT INTO organizations (name, slug, type, country, region, website, is_verified) VALUES
-- ---- India: Government / National Labs ----
('DRDO','drdo','government','India','india','https://www.drdo.gov.in',true),
('ISRO','isro','government','India','india','https://www.isro.gov.in',true),
('CSIR','csir','government','India','india','https://www.csir.res.in',true),
('BARC','barc','government','India','india','https://www.barc.gov.in',true),
('C-DOT','c-dot','government','India','india','https://www.cdot.in',true),
('Semiconductor Laboratory (SCL) Chandigarh','scl-chandigarh','national_lab','India','india','https://www.scl.gov.in',true),
('Space Applications Centre (SAC)','sac-isro','government','India','india','https://www.sac.gov.in',true),
('VSSC','vssc','government','India','india','https://www.vssc.gov.in',true),
-- ---- India: Universities ----
('IISc Bangalore','iisc','academic','India','india','https://www.iisc.ac.in',true),
('IIT Bombay','iit-bombay','academic','India','india','https://www.iitb.ac.in',true),
('IIT Delhi','iit-delhi','academic','India','india','https://home.iitd.ac.in',true),
('IIT Madras','iit-madras','academic','India','india','https://www.iitm.ac.in',true),
('IIT Kanpur','iit-kanpur','academic','India','india','https://www.iitk.ac.in',true),
('IIT Kharagpur','iit-kharagpur','academic','India','india','https://www.iitkgp.ac.in',true),
('IIT Roorkee','iit-roorkee','academic','India','india','https://www.iitr.ac.in',true),
('IIT Guwahati','iit-guwahati','academic','India','india','https://www.iitg.ac.in',true),
('IIT Hyderabad','iit-hyderabad','academic','India','india','https://www.iith.ac.in',true),
('IIST Trivandrum','iist','academic','India','india','https://www.iist.ac.in',true),
('DIAT Pune','diat-pune','academic','India','india','https://www.diat.ac.in',true),
('IIIT Hyderabad','iiit-hyderabad','academic','India','india','https://www.iiit.ac.in',true),
('IIIT Bangalore','iiit-bangalore','academic','India','india','https://www.iiitb.ac.in',true),
('IIIT Delhi','iiit-delhi','academic','India','india','https://www.iiitd.ac.in',true),
('BITS Pilani','bits-pilani','academic','India','india','https://www.bits-pilani.ac.in',true),
('NIT Tiruchirappalli','nit-trichy','academic','India','india','https://www.nitt.edu',true),
('NIT Warangal','nit-warangal','academic','India','india','https://www.nitw.ac.in',true),
('NIT Surathkal','nit-surathkal','academic','India','india','https://www.nitk.ac.in',true),
('TIFR','tifr','academic','India','india','https://www.tifr.res.in',true),
('Anna University','anna-university','academic','India','india','https://www.annauniv.edu',true),
-- ---- Semiconductor IDMs / Manufacturers ----
('Intel','intel','idm','USA','north_america','https://www.intel.com',true),
('TSMC','tsmc','idm','Taiwan','asia_pacific','https://www.tsmc.com',true),
('Samsung Semiconductor','samsung-semi','idm','South Korea','asia_pacific','https://semiconductor.samsung.com',true),
('Micron Technology','micron','idm','USA','north_america','https://www.micron.com',true),
('SK Hynix','sk-hynix','idm','South Korea','asia_pacific','https://www.skhynix.com',true),
('Texas Instruments','texas-instruments','idm','USA','north_america','https://www.ti.com',true),
('Infineon Technologies','infineon','idm','Germany','europe','https://www.infineon.com',true),
('STMicroelectronics','stmicroelectronics','idm','Switzerland','europe','https://www.st.com',true),
('NXP Semiconductors','nxp','idm','Netherlands','europe','https://www.nxp.com',true),
('onsemi','onsemi','idm','USA','north_america','https://www.onsemi.com',true),
('Renesas Electronics','renesas','idm','Japan','asia_pacific','https://www.renesas.com',true),
('Microchip Technology','microchip','idm','USA','north_america','https://www.microchip.com',true),
('Analog Devices','analog-devices','idm','USA','north_america','https://www.analog.com',true),
('Wolfspeed','wolfspeed','idm','USA','north_america','https://www.wolfspeed.com',true),
('GlobalFoundries','globalfoundries','idm','USA','north_america','https://www.globalfoundries.com',true),
('UMC','umc','idm','Taiwan','asia_pacific','https://www.umc.com',true),
('Kioxia','kioxia','idm','Japan','asia_pacific','https://www.kioxia.com',true),
('Western Digital','western-digital','idm','USA','north_america','https://www.westerndigital.com',true),
('SanDisk','sandisk','idm','USA','north_america','https://www.sandisk.com',true),
('Nordic Semiconductor','nordic-semiconductor','idm','Norway','europe','https://www.nordicsemi.com',true),
('Sony Semiconductor Solutions','sony-semi','idm','Japan','asia_pacific','https://www.sony-semicon.com',true),
-- ---- Fabless / Chip Design ----
('NVIDIA','nvidia','fabless','USA','north_america','https://www.nvidia.com',true),
('AMD','amd','fabless','USA','north_america','https://www.amd.com',true),
('Qualcomm','qualcomm','fabless','USA','north_america','https://www.qualcomm.com',true),
('Broadcom','broadcom','fabless','USA','north_america','https://www.broadcom.com',true),
('MediaTek','mediatek','fabless','Taiwan','asia_pacific','https://www.mediatek.com',true),
('Marvell Technology','marvell','fabless','USA','north_america','https://www.marvell.com',true),
('ARM Holdings','arm','fabless','UK','europe','https://www.arm.com',true),
('Cirrus Logic','cirrus-logic','fabless','USA','north_america','https://www.cirrus.com',true),
('Lattice Semiconductor','lattice','fabless','USA','north_america','https://www.latticesemi.com',true),
('Graphcore','graphcore','fabless','UK','europe','https://www.graphcore.ai',true),
('Cerebras Systems','cerebras','fabless','USA','north_america','https://www.cerebras.net',true),
('Groq','groq','fabless','USA','north_america','https://groq.com',true),
('SiFive','sifive','fabless','USA','north_america','https://www.sifive.com',true),
('Tenstorrent','tenstorrent','fabless','USA','north_america','https://tenstorrent.com',true),
('Astera Labs','astera-labs','fabless','USA','north_america','https://www.asteralabs.com',true),
('Credo Technology','credo','fabless','USA','north_america','https://www.credosemi.com',true),
('Ampere Computing','ampere','fabless','USA','north_america','https://www.amperecomputing.com',true),
('VeriSilicon','verisilicon','fabless','China','asia_pacific','https://www.verisilicon.com',true),
('Alphawave Semi','alphawave','fabless','UK','europe','https://awavesemi.com',true),
-- ---- Big Tech In-House Silicon ----
('Google (Silicon)','google-silicon','private','USA','north_america','https://careers.google.com',true),
('Amazon Annapurna Labs','annapurna-labs','private','USA','north_america','https://www.amazon.jobs',true),
('Microsoft (Azure Silicon)','microsoft-silicon','private','USA','north_america','https://careers.microsoft.com',true),
('Meta (MTIA Silicon)','meta-silicon','private','USA','north_america','https://www.metacareers.com',true),
('Apple (Silicon Engineering)','apple-silicon','private','USA','north_america','https://www.apple.com/careers',true),
-- ---- EDA / Design Tools ----
('Synopsys','synopsys','eda','USA','north_america','https://www.synopsys.com',true),
('Cadence Design Systems','cadence','eda','USA','north_america','https://www.cadence.com',true),
('Siemens EDA','siemens-eda','eda','USA','north_america','https://eda.sw.siemens.com',true),
('Ansys','ansys','eda','USA','north_america','https://www.ansys.com',true),
('Silvaco','silvaco','eda','USA','north_america','https://www.silvaco.com',true),
-- ---- Equipment & Materials ----
('ASML','asml','equipment','Netherlands','europe','https://www.asml.com',true),
('Applied Materials','applied-materials','equipment','USA','north_america','https://www.appliedmaterials.com',true),
('Lam Research','lam-research','equipment','USA','north_america','https://www.lamresearch.com',true),
('KLA Corporation','kla','equipment','USA','north_america','https://www.kla.com',true),
('Tokyo Electron','tokyo-electron','equipment','Japan','asia_pacific','https://www.tel.com',true),
('Advantest','advantest','equipment','Japan','asia_pacific','https://www.advantest.com',true),
('Teradyne','teradyne','equipment','USA','north_america','https://www.teradyne.com',true),
('Keysight Technologies','keysight','equipment','USA','north_america','https://www.keysight.com',true),
-- ---- OSAT / Packaging ----
('Amkor Technology','amkor','osat','USA','north_america','https://www.amkor.com',true),
('ASE Technology Holding','ase','osat','Taiwan','asia_pacific','https://www.aseglobal.com',true),
('JCET Group','jcet','osat','China','asia_pacific','https://www.jcetglobal.com',true),
-- ---- International National Labs ----
('imec','imec','national_lab','Belgium','europe','https://www.imec-int.com',true),
('CEA-Leti','cea-leti','national_lab','France','europe','https://www.leti-cea.com',true),
('Fraunhofer','fraunhofer','national_lab','Germany','europe','https://www.fraunhofer.de',true),
('A*STAR IME','astar-ime','national_lab','Singapore','asia_pacific','https://www.a-star.edu.sg',true),
('NIST','nist','national_lab','USA','north_america','https://www.nist.gov',true),
('Sandia National Laboratories','sandia','national_lab','USA','north_america','https://www.sandia.gov',true),
('Oak Ridge National Laboratory','ornl','national_lab','USA','north_america','https://www.ornl.gov',true),
('NASA JPL','nasa-jpl','national_lab','USA','north_america','https://www.jpl.nasa.gov',true),
('RIKEN','riken','national_lab','Japan','asia_pacific','https://www.riken.jp',true),
('ITRI','itri','national_lab','Taiwan','asia_pacific','https://www.itri.org',true),
('ETRI','etri','national_lab','South Korea','asia_pacific','https://www.etri.re.kr',true),
-- ---- Universities: North America ----
('MIT','mit','academic','USA','north_america','https://www.mit.edu',true),
('Stanford University','stanford','academic','USA','north_america','https://www.stanford.edu',true),
('UC Berkeley','uc-berkeley','academic','USA','north_america','https://www.berkeley.edu',true),
('Georgia Tech','georgia-tech','academic','USA','north_america','https://www.gatech.edu',true),
('Purdue University','purdue','academic','USA','north_america','https://www.purdue.edu',true),
('University of Michigan','umich','academic','USA','north_america','https://umich.edu',true),
('UT Austin','ut-austin','academic','USA','north_america','https://www.utexas.edu',true),
('Carnegie Mellon University','cmu','academic','USA','north_america','https://www.cmu.edu',true),
('University of Toronto','uoft','academic','Canada','north_america','https://www.utoronto.ca',true),
('University of Waterloo','waterloo','academic','Canada','north_america','https://uwaterloo.ca',true),
-- ---- Universities: Europe ----
('ETH Zurich','eth-zurich','academic','Switzerland','europe','https://ethz.ch',true),
('EPFL','epfl','academic','Switzerland','europe','https://www.epfl.ch',true),
('TU Delft','tu-delft','academic','Netherlands','europe','https://www.tudelft.nl',true),
('Technical University of Munich','tum','academic','Germany','europe','https://www.tum.de',true),
('RWTH Aachen','rwth-aachen','academic','Germany','europe','https://www.rwth-aachen.de',true),
('KU Leuven','ku-leuven','academic','Belgium','europe','https://www.kuleuven.be',true),
('Imperial College London','imperial','academic','UK','europe','https://www.imperial.ac.uk',true),
('University of Cambridge','cambridge','academic','UK','europe','https://www.cam.ac.uk',true),
('KTH Royal Institute of Technology','kth','academic','Sweden','europe','https://www.kth.se',true),
-- ---- Universities: Asia-Pacific ----
('NUS','nus','academic','Singapore','asia_pacific','https://www.nus.edu.sg',true),
('NTU Singapore','ntu-singapore','academic','Singapore','asia_pacific','https://www.ntu.edu.sg',true),
('Tsinghua University','tsinghua','academic','China','asia_pacific','https://www.tsinghua.edu.cn',true),
('KAIST','kaist','academic','South Korea','asia_pacific','https://www.kaist.ac.kr',true),
('University of Tokyo','u-tokyo','academic','Japan','asia_pacific','https://www.u-tokyo.ac.jp',true),
('National Taiwan University','ntu-taiwan','academic','Taiwan','asia_pacific','https://www.ntu.edu.tw',true),
('HKUST','hkust','academic','Hong Kong','asia_pacific','https://www.hkust.edu.hk',true),
('UNSW Sydney','unsw','academic','Australia','asia_pacific','https://www.unsw.edu.au',true),
('Technion','technion','academic','Israel','asia_pacific','https://www.technion.ac.il',true),
-- ---- Universities: Middle East / LatAm / Africa ----
('KAUST','kaust','academic','Saudi Arabia','middle_east','https://www.kaust.edu.sa',true),
('Khalifa University','khalifa','academic','UAE','middle_east','https://www.ku.ac.ae',true),
('University of Sao Paulo','usp','academic','Brazil','latin_america','https://www5.usp.br',true),
('UNICAMP','unicamp','academic','Brazil','latin_america','https://www.unicamp.br',true),
('University of Cape Town','uct','academic','South Africa','africa','https://www.uct.ac.za',true)
ON CONFLICT (slug) DO NOTHING;
