import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#FAF9F6",
        "bg-secondary": "#FEF9C3",
        surface: "#FFFFFF",
        "surface-elevated": "#FFFFFF",
        border: "#0F172A",
        "border-hover": "#000000",
        accent: "#2563EB",
        "accent-hover": "#1D4ED8",
        "accent-yellow": "#FACC15",
        "accent-glow": "rgba(15, 23, 42, 0.08)",
        success: "#059669",
        warning: "#D97706",
        danger: "#DC2626",
        "text-primary": "#0F172A",
        "text-secondary": "#334155",
        "text-muted": "#64748B",
        "org-isro": "#A0784C",
        "org-intel": "#5B7DB1",
        "org-tifr": "#8B6CB4",
        "org-tata": "#4A8C6F",
        "org-drdo": "#B85450",

        background: "#FAF9F6",
        foreground: "#0F172A",
        card: "#FFFFFF",
        "card-foreground": "#0F172A",
        popover: "#FFFFFF",
        "popover-foreground": "#0F172A",
        primary: "#2563EB",
        "primary-foreground": "#FFFFFF",
        secondary: "#FEF9C3",
        "secondary-foreground": "#0F172A",
        muted: "#E2E8F0",
        "muted-foreground": "#64748B",
        "accent-foreground": "#FFFFFF",
        destructive: "#DC2626",
        "destructive-foreground": "#FFFFFF",
        input: "#FFFFFF",
        ring: "#2563EB",
        navy: "#FAF9F6",
        "navy-light": "#FEF9C3",
        cyan: "#2563EB",
      },
      fontFamily: {
        display: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      fontSize: {
        xxs: "0.625rem",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "14px",
        "2xl": "18px",
        full: "9999px",
        card: "12px",
        pill: "9999px",
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px #0F172A",
        "brutal-lg": "6px 6px 0px 0px #0F172A",
        "brutal-sm": "2px 2px 0px 0px #0F172A",
        card: "4px 4px 0px 0px #0F172A",
        "card-hover": "6px 6px 0px 0px #0F172A",
      },
      backgroundImage: {
        "gradient-hero": "linear-gradient(to right, #22D3EE, #3B82F6)",
        "gradient-deadline": "linear-gradient(to right, #F59E0B, #EF4444)",
        "gradient-card-border": "linear-gradient(to right, transparent, rgba(34, 211, 238, 0.2), transparent)",
        "gradient-radial-cyan": "radial-gradient(ellipse at center, rgba(34, 211, 238, 0.05) 0%, transparent 70%)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
