services:
  # Next.js 14 Application (production-mode preview)
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: siliconpath_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=SiliconPath
      - NEXT_PUBLIC_SITE_URL=https://siliconpath.vercel.app
    restart: always