// src/lib/academy/all-paths.ts

export interface LearningModule {
  slug: string;
  title: string;
  duration: string;
  description: string;
}

export interface LearningPath {
  slug: string;
  title: string;
  level: "Beginner" | "Intermediate" | "Advanced" | "All levels";
  category: "foundations" | "backend" | "tools-career";
  description: string;
  tools: string[];
  moduleCount: number;
  modules: LearningModule[];
}

export const LEARNING_PATHS: LearningPath[] = [
  // ─────────────────────────────────────────────────────
  // FOUNDATIONS (5 paths)
  // ─────────────────────────────────────────────────────
  {
    slug: "digital-electronics",
    title: "Digital Electronics",
    level: "Beginner",
    category: "foundations",
    description: "Master the fundamentals of digital logic, from binary arithmetic to error correction codes.",
    tools: [],
    moduleCount: 11,
    modules: [
      { slug: "number-systems", title: "Number Systems & Binary Arithmetic", duration: "4 min", description: "Understanding binary, hexadecimal, and octal number systems used in digital electronics." },
      { slug: "logic-gates", title: "Logic Gates & Boolean Algebra", duration: "6 min", description: "AND, OR, NOT, NAND, NOR, XOR gates and Boolean algebra fundamentals." },
      { slug: "k-maps", title: "Karnaugh Maps (K-Maps)", duration: "4 min", description: "Simplifying Boolean expressions using Karnaugh maps for efficient circuit design." },
      { slug: "combinational-logic", title: "Combinational Logic Circuits", duration: "4 min", description: "Designing combinational circuits: multiplexers, decoders, and adders." },
      { slug: "sequential-logic", title: "Sequential Logic Circuits", duration: "4 min", description: "Flip-flops, counters, and registers in sequential circuit design." },
      { slug: "fsm", title: "Finite State Machines (FSM)", duration: "2 min", description: "Designing and analyzing finite state machines for control logic." },
      { slug: "interview-qa", title: "Digital Electronics - Interview Q&A", duration: "10 min", description: "Common interview questions and answers for digital electronics fundamentals." },
      { slug: "fast-adders", title: "Fast Adders: Carry Lookahead and Beyond", duration: "9 min", description: "Advanced adder architectures including carry lookahead and carry select adders." },
      { slug: "multipliers", title: "Multipliers and Barrel Shifters", duration: "9 min", description: "Hardware multipliers and barrel shifters for efficient arithmetic operations." },
      { slug: "floating-point", title: "Fixed and Floating Point Representation", duration: "10 min", description: "Number representation formats including IEEE 754 floating point." },
      { slug: "error-detection", title: "Error Detection and Correction: Parity and Hamming", duration: "9 min", description: "Techniques for detecting and correcting errors in digital systems." },
    ],
  },
  {
    slug: "verilog",
    title: "Verilog",
    level: "Beginner",
    category: "foundations",
    description: "Learn Verilog from scratch — from your first module to synthesizable RTL design.",
    tools: ["Verilog"],
    moduleCount: 14,
    modules: [
      { slug: "what-is-verilog", title: "What Verilog Really Is", duration: "6 min", description: "Introduction to Verilog as a hardware description language and its role in chip design." },
      { slug: "first-module", title: "Your First Module", duration: "7 min", description: "Writing your first Verilog module with inputs, outputs, and behavioral modeling." },
      { slug: "wires-regs", title: "Wires, Regs, and the Four Values", duration: "8 min", description: "Understanding wire and reg data types and the four-state logic values." },
      { slug: "operators", title: "Operators You Will Actually Use", duration: "7 min", description: "Essential Verilog operators for bitwise, logical, and arithmetic operations." },
      { slug: "combinational-logic", title: "Combinational Logic", duration: "9 min", description: "Modeling combinational logic with continuous assignments and always blocks." },
      { slug: "if-case", title: "if, case, and Avoiding Latches", duration: "8 min", description: "Using if-else and case statements while avoiding unintended latches." },
      { slug: "sequential-logic", title: "Sequential Logic and the Clock", duration: "10 min", description: "Sequential logic design with clocked always blocks and edge detection." },
      { slug: "blocking-nonblocking", title: "Blocking vs Non-blocking", duration: "9 min", description: "Understanding blocking (=) and non-blocking (<=) assignments and when to use each." },
      { slug: "fsm", title: "Finite State Machines", duration: "11 min", description: "Designing FSMs in Verilog with state encoding and transition logic." },
      { slug: "testbench", title: "Writing a Testbench", duration: "10 min", description: "Creating testbenches to verify Verilog designs with stimulus and checks." },
      { slug: "synthesizable-rtl", title: "Synthesizable RTL and Next Steps", duration: "8 min", description: "Writing synthesizable RTL and preparing for synthesis tools." },
      { slug: "parameters-generate", title: "Parameters and Generate", duration: "9 min", description: "Using parameters and generate statements for scalable Verilog designs." },
      { slug: "rtl-building-blocks", title: "Common RTL Building Blocks", duration: "10 min", description: "Reusable RTL patterns: FIFOs, arbiters, and pipeline registers." },
      { slug: "verilog-to-sv", title: "From Verilog to SystemVerilog", duration: "9 min", description: "Transitioning from Verilog to SystemVerilog for modern design and verification." },
    ],
  },
  {
    slug: "hardware-protocols",
    title: "Hardware Protocols",
    level: "Intermediate",
    category: "foundations",
    description: "Understand the bus and serial protocols that connect chips — from handshakes to AXI.",
    tools: ["AXI", "APB", "AHB", "SPI", "I2C", "UART"],
    moduleCount: 8,
    modules: [
      { slug: "why-protocols", title: "Why Chips Need Protocols", duration: "6 min", description: "The role of communication protocols in modern SoC architectures." },
      { slug: "valid-ready", title: "The VALID/READY Handshake", duration: "8 min", description: "Mastering the fundamental VALID/READY handshake used across protocols." },
      { slug: "apb", title: "APB: The Simple Peripheral Bus", duration: "8 min", description: "AMBA APB protocol for low-bandwidth peripheral connections." },
      { slug: "ahb", title: "AHB: The Pipelined Bus", duration: "8 min", description: "AMBA AHB protocol with burst transfers and pipelined operation." },
      { slug: "axi", title: "AXI: The High-Performance Interface", duration: "11 min", description: "AMBA AXI protocol for high-performance, high-frequency system designs." },
      { slug: "spi", title: "SPI: Fast Four-Wire Serial", duration: "7 min", description: "Serial Peripheral Interface for high-speed chip-to-chip communication." },
      { slug: "i2c", title: "I2C: Two-Wire Addressable Bus", duration: "8 min", description: "Inter-Integrated Circuit protocol for low-speed peripheral communication." },
      { slug: "uart", title: "UART: Clockless Asynchronous Serial", duration: "8 min", description: "Universal Asynchronous Receiver-Transmitter for serial communication." },
    ],
  },
  {
    slug: "design-verification",
    title: "Design Verification",
    level: "Beginner",
    category: "foundations",
    description: "From first testbench to UVM mastery — learn the verification methodologies used in industry.",
    tools: ["SystemVerilog", "UVM"],
    moduleCount: 13,
    modules: [
      { slug: "what-is-verification", title: "What Verification Really Is", duration: "7 min", description: "Understanding the role and importance of design verification in chip development." },
      { slug: "simple-testbench", title: "A Simple Testbench", duration: "8 min", description: "Writing your first testbench to verify a basic digital design." },
      { slug: "sv-for-verification", title: "SystemVerilog for Verification", duration: "9 min", description: "SystemVerilog constructs specifically useful for verification tasks." },
      { slug: "oop-basics", title: "Object-Oriented Basics", duration: "10 min", description: "OOP concepts: classes, inheritance, and polymorphism in SystemVerilog." },
      { slug: "randomization", title: "Randomization and Constraints", duration: "10 min", description: "Constrained random verification with SystemVerilog randomization." },
      { slug: "functional-coverage", title: "Functional Coverage", duration: "9 min", description: "Measuring verification completeness with functional coverage models." },
      { slug: "assertions", title: "Assertions", duration: "9 min", description: "SystemVerilog Assertions (SVA) for checking design behavior." },
      { slug: "uvm-big-picture", title: "UVM - The Big Picture", duration: "11 min", description: "Overview of the Universal Verification Methodology and its components." },
      { slug: "uvm-testbench", title: "Building a UVM Testbench", duration: "10 min", description: "Constructing a complete UVM testbench with driver, monitor, and sequencer." },
      { slug: "uvm-sequences", title: "UVM Sequences and the Sequencer", duration: "11 min", description: "Creating and managing UVM sequences for stimulus generation." },
      { slug: "uvm-ral", title: "UVM RAL: The Register Layer", duration: "11 min", description: "UVM Register Abstraction Layer for register access and verification." },
      { slug: "advanced-random", title: "Advanced Constrained Random", duration: "10 min", description: "Advanced randomization techniques and complex constraint solving." },
      { slug: "advanced-sva", title: "Advanced SVA: Sequences and Properties", duration: "11 min", description: "Complex assertion sequences, properties, and temporal operators." },
    ],
  },
  {
    slug: "clock-domain-crossing",
    title: "Clock Domain Crossing",
    level: "Intermediate",
    category: "foundations",
    description: "Safely transfer data between clock domains — from metastability to async FIFOs.",
    tools: [],
    moduleCount: 8,
    modules: [
      { slug: "why-cdc", title: "Why Clock Domain Crossing Matters", duration: "7 min", description: "Understanding the challenges of multi-clock domain designs." },
      { slug: "metastability", title: "Metastability, Explained", duration: "8 min", description: "Deep dive into metastability, MTBF, and why it happens." },
      { slug: "two-flop", title: "The Two-Flop Synchronizer", duration: "8 min", description: "Implementing and analyzing the two-flop synchronizer for single-bit signals." },
      { slug: "gray-code", title: "Buses and Gray Code", duration: "9 min", description: "Using Gray code for safe multi-bit CDC across clock domains." },
      { slug: "async-fifo", title: "The Asynchronous FIFO", duration: "11 min", description: "Designing async FIFOs with Gray code pointers for reliable data transfer." },
      { slug: "handshake-pulse", title: "Handshake and Pulse Synchronizers", duration: "9 min", description: "Alternative CDC techniques using handshakes and pulse synchronizers." },
      { slug: "reset-sync", title: "Reset Synchronization", duration: "8 min", description: "Synchronizing reset signals across clock domains." },
      { slug: "cdc-verification", title: "CDC Verification and Common Mistakes", duration: "8 min", description: "Techniques for verifying CDC correctness and common pitfalls to avoid." },
    ],
  },

  // ─────────────────────────────────────────────────────
  // BACKEND (RTL to GDSII) (6 paths)
  // ─────────────────────────────────────────────────────
  {
    slug: "synthesis",
    title: "Synthesis",
    level: "Beginner",
    category: "backend",
    description: "Transform RTL into gates — master the synthesis flow from constraints to QoR.",
    tools: ["Synopsys Design Compiler", "Cadence Genus"],
    moduleCount: 11,
    modules: [
      { slug: "intro", title: "Introduction to Synthesis", duration: "3 min", description: "What synthesis is and how it fits into the chip design flow." },
      { slug: "flow", title: "Detailed Synthesis Flow", duration: "1 min", description: "Step-by-step synthesis process from RTL to gate-level netlist." },
      { slug: "dc", title: "Synopsys Design Compiler (DC)", duration: "5 min", description: "Using Design Compiler for logic synthesis and optimization." },
      { slug: "genus", title: "Cadence Genus", duration: "1 min", description: "Introduction to Cadence Genus synthesis tool." },
      { slug: "sdc", title: "Timing Constraints (SDC)", duration: "3 min", description: "Writing Synopsys Design Constraints for timing and area." },
      { slug: "optimization", title: "Optimization Techniques", duration: "1 min", description: "Key optimization strategies in synthesis for timing and area." },
      { slug: "qor", title: "Quality of Results (QoR)", duration: "2 min", description: "Evaluating synthesis quality through timing, area, and power metrics." },
      { slug: "retiming", title: "Retiming: Moving Registers to Balance Logic", duration: "9 min", description: "Using retiming to improve timing by redistributing registers." },
      { slug: "hierarchy", title: "Hierarchy: Ungroup, Flatten, and Boundary Optimization", duration: "9 min", description: "Managing design hierarchy for optimal synthesis results." },
      { slug: "power-aware", title: "Power-Aware Synthesis: Clock Gating and Multi-Vt", duration: "10 min", description: "Techniques for reducing power consumption during synthesis." },
      { slug: "dft-scan", title: "DFT and Scan-Aware Synthesis", duration: "9 min", description: "Integrating design-for-test structures during synthesis." },
    ],
  },
  {
    slug: "physical-design",
    title: "Physical Design",
    level: "Intermediate",
    category: "backend",
    description: "From floorplan to tapeout — master the physical implementation of digital chips.",
    tools: ["Synopsys ICC2", "Cadence Innovus"],
    moduleCount: 11,
    modules: [
      { slug: "intro", title: "Introduction to Physical Design", duration: "2 min", description: "Overview of the physical design flow and its role in chip implementation." },
      { slug: "floorplan", title: "Floorplanning", duration: "7 min", description: "Creating chip floorplans with macro placement and pin assignment." },
      { slug: "power-plan", title: "Power Planning", duration: "3 min", description: "Designing power distribution networks with rings, straps, and rails." },
      { slug: "placement", title: "Placement", duration: "2 min", description: "Standard cell placement and timing-driven placement optimization." },
      { slug: "cts", title: "Clock Tree Synthesis (CTS)", duration: "3 min", description: "Building balanced clock trees for minimal skew and insertion delay." },
      { slug: "routing", title: "Routing", duration: "3 min", description: "Signal routing with congestion and timing awareness." },
      { slug: "pv", title: "Physical Verification", duration: "1 min", description: "Running DRC, LVS, and ERC checks on the physical design." },
      { slug: "pd-tools", title: "PD Tool Knowledge", duration: "1 min", description: "Key physical design tools and their capabilities." },
      { slug: "congestion", title: "Congestion Analysis and Fixes", duration: "9 min", description: "Identifying and resolving routing congestion issues." },
      { slug: "ir-drop", title: "IR Drop and Power Integrity", duration: "9 min", description: "Analyzing and fixing IR drop issues in power distribution." },
      { slug: "eco", title: "The ECO Flow", duration: "8 min", description: "Engineering Change Orders for late-stage design modifications." },
    ],
  },
  {
    slug: "static-timing-analysis",
    title: "Static Timing Analysis",
    level: "Intermediate",
    category: "backend",
    description: "Analyze timing paths, close timing, and ensure your design meets specs.",
    tools: ["Synopsys PrimeTime", "Cadence Tempus"],
    moduleCount: 13,
    modules: [
      { slug: "intro", title: "Introduction to STA", duration: "3 min", description: "What STA is and why it's essential for digital design verification." },
      { slug: "path-types", title: "Timing Path Types", duration: "2 min", description: "Understanding different timing paths: register-to-register, input-to-register." },
      { slug: "setup-hold", title: "Setup & Hold Slack Analysis", duration: "2 min", description: "Calculating setup and hold slack for timing violations." },
      { slug: "cdc", title: "Clock Domain Crossing (CDC)", duration: "4 min", description: "Timing analysis across different clock domains." },
      { slug: "ocv-aocv", title: "On-Chip Variation (OCV) & AOCV", duration: "1 min", description: "Accounting for manufacturing variations in timing analysis." },
      { slug: "mmmc", title: "Multi-Mode Multi-Corner (MMMC)", duration: "1 min", description: "Analyzing timing across multiple operating conditions." },
      { slug: "primetime", title: "Synopsys PrimeTime", duration: "2 min", description: "Using PrimeTime for signoff static timing analysis." },
      { slug: "tempus", title: "Cadence Tempus", duration: "1 min", description: "Introduction to Cadence Tempus timing signoff tool." },
      { slug: "closure", title: "Timing Closure Techniques", duration: "1 min", description: "Strategies for achieving timing closure in complex designs." },
      { slug: "latch-borrowing", title: "Latch Borrowing", duration: "3 min", description: "Understanding time borrowing in latch-based designs." },
      { slug: "crpr", title: "CRPR: Removing Clock Pessimism", duration: "8 min", description: "Clock Reconvergence Pessimism Removal for accurate timing." },
      { slug: "graph-path", title: "Graph-Based vs Path-Based Analysis", duration: "8 min", description: "Comparing graph-based and path-based STA approaches." },
      { slug: "crosstalk", title: "Crosstalk and Signal Integrity", duration: "9 min", description: "Impact of crosstalk on timing and signal integrity analysis." },
    ],
  },
  {
    slug: "physical-verification",
    title: "Physical Verification",
    level: "Intermediate",
    category: "backend",
    description: "Ensure your layout is manufacturable — DRC, LVS, ERC, and advanced checks.",
    tools: ["Synopsys IC Validator", "Cadence Pegasus"],
    moduleCount: 12,
    modules: [
      { slug: "overview", title: "Overview", duration: "1 min", description: "Introduction to physical verification in the chip design flow." },
      { slug: "pv-flow", title: "PV Flow Overview", duration: "1 min", description: "The complete physical verification process and signoff checks." },
      { slug: "drc", title: "DRC - Design Rule Check", duration: "4 min", description: "Running and fixing design rule violations for manufacturability." },
      { slug: "lvs", title: "LVS - Layout vs. Schematic", duration: "3 min", description: "Verifying layout matches the schematic design intent." },
      { slug: "erc", title: "ERC - Electrical Rule Check", duration: "1 min", description: "Checking for electrical rule violations and reliability issues." },
      { slug: "antenna", title: "Antenna Check", duration: "1 min", description: "Preventing antenna effects during metal layer processing." },
      { slug: "metal-fill", title: "Metal Fill & Density Rules", duration: "2 min", description: "Adding metal fill to meet density requirements for manufacturing." },
      { slug: "pv-tools", title: "PV Tool Knowledge", duration: "2 min", description: "Key physical verification tools and their capabilities." },
      { slug: "pv-interview", title: "Physical Verification - Interview Questions", duration: "6 min", description: "Common interview questions for physical verification roles." },
      { slug: "multi-patterning", title: "Multi-Patterning and Coloring Checks", duration: "10 min", description: "Advanced patterning techniques and coloring rule verification." },
      { slug: "dfm", title: "DFM and Lithography Hotspots", duration: "10 min", description: "Design for manufacturability and lithography analysis." },
      { slug: "lvs-debug", title: "LVS Debugging Methodology", duration: "11 min", description: "Systematic approach to debugging LVS mismatches." },
    ],
  },
  {
    slug: "low-power-design-upf",
    title: "Low Power Design & UPF",
    level: "Advanced",
    category: "backend",
    description: "Master power management — from clock gating to UPF-based power-aware design.",
    tools: ["UPF", "Synopsys LP Tools", "Cadence CPF"],
    moduleCount: 13,
    modules: [
      { slug: "overview", title: "Overview", duration: "1 min", description: "Introduction to low power design and its importance in modern chips." },
      { slug: "why-low-power", title: "Why Low Power Matters", duration: "1 min", description: "Understanding the impact of power consumption on chip design." },
      { slug: "clock-gating", title: "Clock Gating (ICG)", duration: "2 min", description: "Reducing dynamic power with integrated clock gating cells." },
      { slug: "multi-vt", title: "Multi-Threshold Voltage (Multi-Vt)", duration: "2 min", description: "Using multiple threshold voltages to optimize power and performance." },
      { slug: "power-domains", title: "Power Domains & Voltage Islands", duration: "1 min", description: "Creating separate power domains for independent voltage control." },
      { slug: "level-shifters", title: "Level Shifters & Isolation Cells", duration: "2 min", description: "Components for safe communication between power domains." },
      { slug: "retention", title: "Retention Registers", duration: "1 min", description: "Preserving state during power-down modes with retention elements." },
      { slug: "power-gating", title: "Power Gating (MTCMOS)", duration: "1 min", description: "Completely shutting off power to inactive blocks." },
      { slug: "upf", title: "UPF - Unified Power Format", duration: "3 min", description: "The IEEE standard for specifying power intent in designs." },
      { slug: "lp-interview", title: "Low Power Interview Questions (Top 15)", duration: "10 min", description: "Common interview questions for low power design roles." },
      { slug: "dvfs", title: "Dynamic Voltage and Frequency Scaling", duration: "9 min", description: "Techniques for dynamically adjusting voltage and frequency." },
      { slug: "power-estimation", title: "Power Estimation and Analysis", duration: "9 min", description: "Methods for estimating and analyzing power consumption." },
      { slug: "upf-states", title: "UPF Power States and the Power State Table", duration: "9 min", description: "Defining and managing power states with UPF." },
    ],
  },
  {
    slug: "design-for-test",
    title: "Design for Test",
    level: "Intermediate",
    category: "backend",
    description: "Make your chips testable — scan chains, ATPG, MBIST, and DFT flows.",
    tools: ["Synopsys DFT Compiler", "Cadence Modus"],
    moduleCount: 8,
    modules: [
      { slug: "why-dft", title: "Why Design for Test Exists", duration: "7 min", description: "The importance of testability in manufactured chips." },
      { slug: "fault-models", title: "Fault Models and Coverage", duration: "8 min", description: "Understanding fault models and measuring test coverage." },
      { slug: "scan-design", title: "Scan Design", duration: "10 min", description: "Implementing scan chains for comprehensive test access." },
      { slug: "atpg", title: "ATPG: Generating the Patterns", duration: "9 min", description: "Automatic Test Pattern Generation for stuck-at and transition faults." },
      { slug: "scan-compression", title: "Scan Compression", duration: "7 min", description: "Reducing test time and data volume with scan compression." },
      { slug: "mbist", title: "Memory BIST", duration: "8 min", description: "Built-in self-test for embedded memories." },
      { slug: "jtag", title: "Boundary Scan and JTAG", duration: "8 min", description: "IEEE 1149.1 boundary scan for board-level testing." },
      { slug: "dft-flow", title: "DFT in the Design Flow", duration: "7 min", description: "Integrating DFT into the overall chip design flow." },
    ],
  },

  // ─────────────────────────────────────────────────────
  // TOOLS & CAREER (4 paths)
  // ─────────────────────────────────────────────────────
  {
    slug: "tcl-for-eda",
    title: "TCL for EDA",
    level: "Beginner",
    category: "tools-career",
    description: "Learn the scripting language that powers every EDA tool — from variables to report parsing.",
    tools: ["TCL"],
    moduleCount: 7,
    modules: [
      { slug: "why-tcl", title: "Why TCL Runs the EDA World", duration: "6 min", description: "Understanding why TCL is the standard scripting language for EDA tools." },
      { slug: "variables", title: "Variables and Substitution", duration: "8 min", description: "TCL variables, substitution rules, and expression evaluation." },
      { slug: "lists", title: "Lists, the TCL Workhorse", duration: "8 min", description: "Working with TCL lists for data manipulation and iteration." },
      { slug: "control-flow", title: "Control Flow", duration: "7 min", description: "if/else, for, while, and foreach loops in TCL." },
      { slug: "procedures", title: "Procedures and Reuse", duration: "7 min", description: "Writing reusable TCL procedures with arguments and return values." },
      { slug: "parsing-reports", title: "Parsing Reports", duration: "9 min", description: "Extracting information from EDA tool reports using TCL." },
      { slug: "tcl-in-eda", title: "TCL Inside EDA Tools", duration: "9 min", description: "Using TCL effectively within Synopsys and Cadence EDA tools." },
    ],
  },
  {
    slug: "linux-for-vlsi",
    title: "Linux for VLSI",
    level: "Beginner",
    category: "tools-career",
    description: "Navigate the Linux environment where all VLSI work happens — from shells to remote servers.",
    tools: ["Linux", "Bash"],
    moduleCount: 7,
    modules: [
      { slug: "why-linux", title: "Why VLSI Runs on Linux", duration: "6 min", description: "Understanding Linux as the standard platform for chip design." },
      { slug: "filesystem", title: "Moving Around the Filesystem", duration: "7 min", description: "Navigating directories and understanding the Linux filesystem hierarchy." },
      { slug: "files", title: "Working with Files", duration: "7 min", description: "Creating, copying, moving, and deleting files in Linux." },
      { slug: "text", title: "Viewing and Searching Text", duration: "8 min", description: "Using cat, grep, awk, and sed for text processing." },
      { slug: "pipes", title: "Pipes and Redirection", duration: "8 min", description: "Chaining commands with pipes and redirecting input/output." },
      { slug: "permissions", title: "Permissions, Processes, and Environment", duration: "8 min", description: "Managing file permissions, processes, and environment variables." },
      { slug: "remote", title: "Remote Servers and Scripting", duration: "9 min", description: "SSH, scripting, and working with remote design servers." },
    ],
  },
  {
    slug: "interview-qa",
    title: "Interview Q&A",
    level: "All levels",
    category: "tools-career",
    description: "Ace your VLSI interviews — curated questions for synthesis, PD, and STA roles.",
    tools: [],
    moduleCount: 5,
    modules: [
      { slug: "synthesis-qa", title: "Synthesis Interview Questions (Top 30)", duration: "12 min", description: "Most common synthesis interview questions with detailed answers." },
      { slug: "pd-qa", title: "Physical Design Interview Questions (Top 30)", duration: "14 min", description: "Top physical design interview questions covering all PD topics." },
      { slug: "sta-qa", title: "STA Interview Questions (Top 35)", duration: "19 min", description: "Comprehensive STA interview questions for timing analysis roles." },
      { slug: "formula-sheet", title: "Formula Cheatsheet", duration: "1 min", description: "Quick reference for essential VLSI formulas and calculations." },
      { slug: "glossary", title: "VLSI Glossary", duration: "9 min", description: "Comprehensive glossary of VLSI terms and abbreviations." },
    ],
  },
  {
    slug: "career-roadmap",
    title: "Career Roadmap",
    level: "All levels",
    category: "tools-career",
    description: "Plan your VLSI career — from choosing a domain to landing your first role.",
    tools: [],
    moduleCount: 9,
    modules: [
      { slug: "overview", title: "Overview", duration: "1 min", description: "High-level overview of the VLSI career landscape." },
      { slug: "domains", title: "VLSI Domains - Which One Is For You?", duration: "1 min", description: "Exploring different VLSI domains and finding your fit." },
      { slug: "roadmap", title: "Learning Roadmap - Fresher to Professional", duration: "1 min", description: "Step-by-step learning path from student to industry professional." },
      { slug: "tools", title: "Essential Tools - What to Learn and How", duration: "3 min", description: "Which EDA tools to learn and how to get hands-on experience." },
      { slug: "interview-plan", title: "Interview Preparation Plan - 8 Weeks", duration: "2 min", description: "Structured 8-week plan for VLSI interview preparation." },
      { slug: "what-interviewers-eval", title: "What Interviewers Actually Evaluate", duration: "2 min", description: "Understanding what hiring managers look for in candidates." },
      { slug: "resources", title: "Essential Books, Courses & Resources", duration: "1 min", description: "Curated list of the best learning resources for VLSI." },
      { slug: "day-in-life", title: "A Day in the Life - By Role", duration: "5 min", description: "What a typical day looks like for different VLSI roles." },
      { slug: "skills-matrix", title: "Skills Proficiency Matrix", duration: "2 min", description: "Mapping skills to proficiency levels for career advancement." },
    ],
  },
];
