import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#0A0E1A",
        "bg-secondary": "#0B0F1C",
        surface: "#111827",
        "surface-elevated": "#141B2D",
        border: "#1E2A3F",
        "border-hover": "#22D3EE33",
        accent: "#22D3EE",
        "accent-hover": "#06B6D4",
        "accent-glow": "rgba(34, 211, 238, 0.15)",
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
        "text-primary": "#F8FAFC",
        "text-secondary": "#94A3B8",
        "text-muted": "#64748B",
        "org-isro": "#A0784C",
        "org-intel": "#5B7DB1",
        "org-tifr": "#8B6CB4",
        "org-tata": "#4A8C6F",
        "org-drdo": "#B85450",

        background: "#0A0E1A",
        foreground: "#F8FAFC",
        card: "#111827",
        "card-foreground": "#F8FAFC",
        popover: "#141B2D",
        "popover-foreground": "#F8FAFC",
        primary: "#22D3EE",
        "primary-foreground": "#0A0E1A",
        secondary: "#141B2D",
        "secondary-foreground": "#F8FAFC",
        muted: "#1E2A3F",
        "muted-foreground": "#94A3B8",
        "accent-foreground": "#0A0E1A",
        destructive: "#EF4444",
        "destructive-foreground": "#F8FAFC",
        input: "#141B2D",
        ring: "#22D3EE",
        navy: "#0A0E1A",
        "navy-light": "#141B2D",
        cyan: "#22D3EE",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      fontSize: {
        xxs: "0.625rem",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
        card: "12px",
        pill: "9999px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.3)",
        "card-hover": "0 0 24px rgba(34, 211, 238, 0.08)",
        "glow-cyan": "0 0 24px rgba(34, 211, 238, 0.15)",
        "glow-sm": "0 0 20px rgba(34, 211, 238, 0.06)",
        "card-dark": "0 4px 24px rgba(0, 0, 0, 0.3)",
        "glow-btn": "0 0 24px rgba(34, 211, 238, 0.2)",
      },
      backgroundImage: {
        "gradient-hero": "linear-gradient(to right, #22D3EE, #3B82F6)",
        "gradient-deadline": "linear-gradient(to right, #F59E0B, #EF4444)",
        "gradient-card-border": "linear-gradient(to right, transparent, rgba(34, 211, 238, 0.2), transparent)",
        "gradient-radial-cyan": "radial-gradient(ellipse at center, rgba(34, 211, 238, 0.05) 0%, transparent 70%)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
