const CITY_COUNTRY_MAP: Record<string, string> = {
  mumbai: "IN",
  delhi: "IN",
  bangalore: "IN",
  bengaluru: "IN",
  hyderabad: "IN",
  chennai: "IN",
  pune: "IN",
  kolkata: "IN",
  ahmedabad: "IN",
  jaipur: "IN",
  lucknow: "IN",
  nagpur: "IN",
  indore: "IN",
  bhopal: "IN",
  chandigarh: "IN",
  gurgaon: "IN",
  gurugram: "IN",
  noida: "IN",
  new_delhi: "IN",
  "new york": "US",
  san_francisco: "US",
  "los angeles": "US",
  seattle: "US",
  austin: "US",
  boston: "US",
  chicago: "US",
  denver: "US",
  atlanta: "US",
  dallas: "US",
  houston: "US",
  miami: "US",
  phoenix: "US",
  san_jose: "US",
  portland: "US",
  washington: "US",
  pittsburgh: "US",
  raleigh: "US",
  dublin: "IE",
  london: "GB",
  manchester: "GB",
  edinburgh: "GB",
  cambridge: "GB",
  oxford: "GB",
  paris: "FR",
  lyon: "FR",
  munich: "DE",
  berlin: "DE",
  frankfurt: "DE",
  hamburg: "DE",
  stuttgart: "DE",
  amsterdam: "NL",
  rotterdam: "NL",
  zurich: "CH",
  geneva: "CH",
  tokyo: "JP",
  osaka: "JP",
  kyoto: "JP",
  beijing: "CN",
  shanghai: "CN",
  shenzhen: "CN",
  guangzhou: "CN",
  hangzhou: "CN",
  seoul: "KR",
  busan: "KR",
  singapore: "SG",
  sydney: "AU",
  melbourne: "AU",
  toronto: "CA",
  vancouver: "CA",
  montreal: "CA",
  ottawa: "CA",
  sao_paulo: "BR",
  rio_de_janeiro: "BR",
  mexico_city: "MX",
  bangkok: "TH",
  ho_chi_minh: "VN",
  hanoi: "VN",
  kuala_lumpur: "MY",
  jakarta: "ID",
  manila: "PH",
  taipei: "TW",
  hong_kong: "HK",
  dubai: "AE",
  abu_dhabi: "AE",
  tel_aviv: "IL",
  jerusalem: "IL",
  istanbul: "TR",
  ankara: "TR",
  moscow: "RU",
  st_petersburg: "RU",
  warsaw: "PL",
  prague: "CZ",
  vienna: "AT",
  stockholm: "SE",
  oslo: "NO",
  copenhagen: "DK",
  helsinki: "FI",
  rome: "IT",
  milan: "IT",
  madrid: "ES",
  barcelona: "ES",
  lisbon: "PT",
  athens: "GR",
  cape_town: "ZA",
  johannesburg: "ZA",
  cairo: "EG",
  nairobi: "KE",
  lagos: "NG",
  buenos_aires: "AR",
  santiago: "CL",
  bogota: "CO",
  lima: "PE",
  wellington: "NZ",
  karachi: "PK",
  lahore: "PK",
  dhaka: "BD",
  colombo: "LK",
  kathmandu: "NP",
};

const COUNTRY_ALIASES: Record<string, string> = {
  india: "IN",
  indian: "IN",
  bharat: "IN",
  usa: "US",
  "united states": "US",
  "united states of america": "US",
  america: "US",
  "united kingdom": "GB",
  uk: "GB",
  britain: "GB",
  england: "GB",
  germany: "DE",
  deutsch: "DE",
  france: "FR",
  japan: "JP",
  chinese: "CN",
  china: "CN",
  korea: "KR",
  "south korea": "KR",
  singapore: "SG",
  australia: "AU",
  canada: "CA",
  brazil: "BR",
  mexico: "MX",
  "hong kong": "HK",
  taiwan: "TW",
  netherlands: "NL",
  holland: "NL",
  switzerland: "CH",
  swiss: "CH",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  italy: "IT",
  italian: "IT",
  spain: "ES",
  spanish: "ES",
  portugal: "PT",
  ireland: "IE",
  israel: "IL",
  uae: "AE",
  "united arab emirates": "AE",
  dubai: "AE",
  "saudi arabia": "SA",
  "south africa": "ZA",
  egypt: "EG",
  nigeria: "NG",
  kenya: "KE",
  russia: "RU",
  russian: "RU",
  poland: "PL",
  "czech republic": "CZ",
  czechia: "CZ",
  austria: "AT",
  greece: "GR",
  turkey: "TR",
  turkiye: "TR",
  argentina: "AR",
  chile: "CL",
  colombia: "CO",
  peru: "PE",
  "new zealand": "NZ",
  pakistan: "PK",
  bangladesh: "BD",
  sri_lanka: "LK",
  nepal: "NP",
  thailand: "TH",
  vietnam: "VN",
  malaysia: "MY",
  indonesia: "ID",
  philippines: "PH",
};

const INDIAN_STATES = new Set([
  "andhra pradesh",
  "arunachal pradesh",
  "assam",
  "bihar",
  "chhattisgarh",
  "goa",
  "gujarat",
  "haryana",
  "himachal pradesh",
  "jharkhand",
  "karnataka",
  "kerala",
  "madhya pradesh",
  "maharashtra",
  "manipur",
  "meghalaya",
  "mizoram",
  "nagaland",
  "odisha",
  "punjab",
  "rajasthan",
  "sikkim",
  "tamil nadu",
  "telangana",
  "tripura",
  "uttar pradesh",
  "uttarakhand",
  "west bengal",
  "delhi",
  "jammu and kashmir",
  "ladakh",
  "chandigarh",
  "puducherry",
  "andaman and nicobar islands",
  "dadra and nagar haveli",
  "daman and diu",
  "lakshadweep",
]);

export class CountryDetector {
  detect(location: string | null, timezone?: string): string {
    if (!location) {
      if (timezone) {
        const upper = timezone.toUpperCase();
        for (const [tz, code] of Object.entries({
          "Asia/Kolkata": "IN",
          "America/New_York": "US",
          "America/Chicago": "US",
          "America/Denver": "US",
          "America/Los_Angeles": "US",
          "Europe/London": "GB",
          "Europe/Berlin": "DE",
          "Europe/Paris": "FR",
          "Asia/Tokyo": "JP",
          "Asia/Shanghai": "CN",
          "Asia/Seoul": "KR",
          "Asia/Singapore": "SG",
          "Australia/Sydney": "AU",
          "America/Toronto": "CA",
          "Europe/Amsterdam": "NL",
          "Europe/Zurich": "CH",
        })) {
          if (upper === tz.toUpperCase()) return code;
        }
      }
      return "";
    }

    const lower = location.toLowerCase().trim();

    for (const [city, country] of Object.entries(CITY_COUNTRY_MAP)) {
      if (lower.includes(city.replace(/_/g, " "))) return country;
    }

    for (const [alias, code] of Object.entries(COUNTRY_ALIASES)) {
      if (lower.includes(alias)) return code;
    }

    for (const state of INDIAN_STATES) {
      if (lower.includes(state)) return "IN";
    }

    return "";
  }
}
