import { SourceConfig } from "./types.js";

export const SOURCES: SourceConfig[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 1: India Government/PSU + Top 10 Global Semiconductor  (30, active)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "intel", name: "Intel", type: "greenhouse", url: "https://jobs.intel.com/", category: "semiconductor-idm", batch: 1, active: true },
  { id: "tsmc", name: "TSMC", type: "workday", url: "https://tsmc.wd3.myworkdayjobs.com/en-US/EXTERNAL_TSMC_CAREERS", category: "semiconductor-idm", batch: 1, active: true },
  { id: "samsung-semiconductor", name: "Samsung Semiconductor", type: "workday", url: "https://semiconductor.samsung.com/careers/", category: "semiconductor-idm", batch: 1, active: true },
  { id: "micron", name: "Micron Technology", type: "workday", url: "https://micron.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 1, active: true },
  { id: "texas-instruments", name: "Texas Instruments", type: "workday", url: "https://careers.ti.com/", category: "semiconductor-idm", batch: 1, active: true },
  { id: "infineon", name: "Infineon Technologies", type: "workday", url: "https://infineon.wd3.myworkdayjobs.com/", category: "semiconductor-idm", batch: 1, active: true },
  { id: "intel-india", name: "Intel India", type: "greenhouse", url: "https://jobs.intel.com/", category: "semiconductor-idm", batch: 1, active: true },
  { id: "nvidia", name: "NVIDIA", type: "workday", url: "https://nvidia.wd5.myworkdayjobs.com/", category: "fabless", batch: 1, active: true },
  { id: "amd", name: "AMD", type: "workday", url: "https://amd.wd1.myworkdayjobs.com/", category: "fabless", batch: 1, active: true },
  { id: "qualcomm", name: "Qualcomm", type: "workday", url: "https://qualcomm.wd5.myworkdayjobs.com/", category: "fabless", batch: 1, active: true },
  { id: "broadcom", name: "Broadcom", type: "workday", url: "https://broadcom.wd1.myworkdayjobs.com/", category: "fabless", batch: 1, active: true },
  { id: "mediatek", name: "MediaTek", type: "workday", url: "https://mediatek.wd5.myworkdayjobs.com/", category: "fabless", batch: 1, active: true },
  { id: "asml", name: "ASML", type: "workday", url: "https://asml.wd3.myworkdayjobs.com/", category: "equipment", batch: 1, active: true },
  { id: "applied-materials", name: "Applied Materials", type: "workday", url: "https://appliedmaterials.wd1.myworkdayjobs.com/", category: "equipment", batch: 1, active: true },
  { id: "synopsys", name: "Synopsys", type: "workday", url: "https://synopsys.wd1.myworkdayjobs.com/", category: "eda", batch: 1, active: true },
  { id: "cadence", name: "Cadence Design Systems", type: "workday", url: "https://cadence.wd1.myworkdayjobs.com/", category: "eda", batch: 1, active: true },
  { id: "drdo", name: "DRDO", type: "html", url: "https://www.drdo.gov.in/careers", category: "national-lab-india", batch: 1, active: true },
  { id: "isro", name: "ISRO", type: "html", url: "https://www.isro.gov.in/careers", category: "national-lab-india", batch: 1, active: true },
  { id: "csir", name: "CSIR", type: "html", url: "https://www.csir.res.in/recruitment", category: "national-lab-india", batch: 1, active: true },
  { id: "barc", name: "BARC", type: "html", url: "https://www.barc.gov.in/careers", category: "national-lab-india", batch: 1, active: true },
  { id: "iit-bombay", name: "IIT Bombay", type: "html", url: "https://www.iitb.ac.in/en/careers", category: "university-india", batch: 1, active: true },
  { id: "iit-delhi", name: "IIT Delhi", type: "html", url: "https://home.iitd.ac.in/careers.php", category: "university-india", batch: 1, active: true },
  { id: "iisc", name: "IISc Bangalore", type: "html", url: "https://www.iisc.ac.in/careers/", category: "university-india", batch: 1, active: true },
  { id: "bits-pilani", name: "BITS Pilani", type: "html", url: "https://www.bits-pilani.ac.in/careers/", category: "university-india", batch: 1, active: true },
  { id: "ece-opportunities-rss", name: "IEEE ECE Job Feed", type: "rss", url: "https://feeds.feedburner.com/IEEEJobs", category: "news-rss", batch: 1, active: false },
  { id: "india-academic-rss", name: "India Academic RSS", type: "rss", url: "https://www.indiaacademic.com/rss/", category: "opportunity-rss", batch: 1, active: false },
  { id: "semiconductor-engineering-rss", name: "Semiconductor Engineering", type: "rss", url: "https://semiengineering.com/feed/", category: "news-rss", batch: 1, active: true },
  { id: "scl-chandigarh", name: "Semiconductor Lab Chandigarh", type: "html", url: "https://www.scl.gov.in/careers", category: "national-lab-india", batch: 1, active: true },
  { id: "imec", name: "imec", type: "workday", url: "https://imec.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 1, active: true },
  { id: "cea-leti", name: "CEA-Leti", type: "html", url: "https://www.leti-cea.fr/cea-leti/Pages/careers.aspx", category: "national-lab-intl", batch: 1, active: true },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 2: Remaining IDMs + Fabless Companies  (~32, inactive until verified)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "sk-hynix", name: "SK Hynix", type: "workday", url: "https://skhynix.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "stmicroelectronics", name: "STMicroelectronics", type: "workday", url: "https://stmicroelectronics.wd3.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "nxp", name: "NXP Semiconductors", type: "workday", url: "https://nxp.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "onsemi", name: "onsemi", type: "workday", url: "https://onsemi.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "renesas", name: "Renesas Electronics", type: "workday", url: "https://renesas.wd3.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "rohm", name: "ROHM Semiconductor", type: "html", url: "https://www.rohm.com/careers", category: "semiconductor-idm", batch: 2, active: false },
  { id: "microchip", name: "Microchip Technology", type: "workday", url: "https://microchip.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "analog-devices", name: "Analog Devices", type: "workday", url: "https://analogdevices.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "skyworks", name: "Skyworks Solutions", type: "workday", url: "https://skyworks.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "qorvo", name: "Qorvo", type: "workday", url: "https://qorvo.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "wolfspeed", name: "Wolfspeed", type: "workday", url: "https://wolfspeed.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "globalfoundries", name: "GlobalFoundries", type: "workday", url: "https://globalfoundries.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "umc", name: "UMC", type: "html", url: "https://www.umc.com/en/Home/careers", category: "semiconductor-idm", batch: 2, active: false },
  { id: "smic", name: "SMIC", type: "html", url: "https://www.smic.com/en/careers", category: "semiconductor-idm", batch: 2, active: false },
  { id: "powerchip", name: "Powerchip Semiconductor", type: "html", url: "https://www.powerchip.com/careers", category: "semiconductor-idm", batch: 2, active: false },
  { id: "vanguard-intl", name: "Vanguard International Semiconductor", type: "html", url: "https://www.vis.com/careers", category: "semiconductor-idm", batch: 2, active: false },
  { id: "tower-semiconductor", name: "Tower Semiconductor", type: "workday", url: "https://towersemi.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "x-fab", name: "X-FAB", type: "html", url: "https://www.xfab.com/careers", category: "semiconductor-idm", batch: 2, active: false },
  { id: "nexperia", name: "Nexperia", type: "workday", url: "https://nexperia.wd3.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "vishay", name: "Vishay Intertechnology", type: "html", url: "https://www.vishay.com/company/careers/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "diodes-inc", name: "Diodes Incorporated", type: "html", url: "https://www.diodes.com/about/careers/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "toshiba-eden", name: "Toshiba Electronic Devices", type: "html", url: "https://www.toshiba.semicon-storage.com/ap-en/company/careers.html", category: "semiconductor-idm", batch: 2, active: false },
  { id: "sony-semi", name: "Sony Semiconductor Solutions", type: "html", url: "https://www.sony-semicon.com/en/careers/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "panasonic-semi", name: "Panasonic Semiconductor", type: "html", url: "https://www.panasonic.com/global/electronics/careers.html", category: "semiconductor-idm", batch: 2, active: false },
  { id: "kioxia", name: "Kioxia", type: "workday", url: "https://kioxia.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "western-digital", name: "Western Digital", type: "workday", url: "https://westerndigital.wd1.myworkdayjobs.com/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "winbond", name: "Winbond Electronics", type: "html", url: "https://www.winbond.com/hq/about-winbond/careers/", category: "semiconductor-idm", batch: 2, active: false },
  { id: "nordic-semi", name: "Nordic Semiconductor", type: "smartrecruiters", url: "https://careers.smartrecruiters.com/NordicSemiconductor", category: "semiconductor-idm", batch: 2, active: false },
  { id: "marvell", name: "Marvell Technology", type: "workday", url: "https://marvell.wd1.myworkdayjobs.com/", category: "fabless", batch: 2, active: false },
  { id: "apple-silicon", name: "Apple Silicon Engineering", type: "workday", url: "https://apple.wd1.myworkdayjobs.com/", category: "fabless", batch: 2, active: false },
  { id: "arm", name: "ARM Holdings", type: "workday", url: "https://arm.wd3.myworkdayjobs.com/", category: "fabless", batch: 2, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 3: More Fabless + Equipment + Materials  (~30, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "cirrus-logic", name: "Cirrus Logic", type: "workday", url: "https://cirrus.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "synaptics", name: "Synaptics", type: "workday", url: "https://synaptics.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "lattice-semi", name: "Lattice Semiconductor", type: "workday", url: "https://lattice.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "ambiq-micro", name: "Ambiq Micro", type: "workday", url: "https://ambiq.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "graphcore", name: "Graphcore", type: "greenhouse", url: "https://graphcore.ai/careers", category: "fabless", batch: 3, active: false },
  { id: "cerebras", name: "Cerebras Systems", type: "greenhouse", url: "https://cerebras.net/careers/", category: "fabless", batch: 3, active: false },
  { id: "groq-ai", name: "Groq", type: "workday", url: "https://groq.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "sifive", name: "SiFive", type: "greenhouse", url: "https://sifive.com/careers", category: "fabless", batch: 3, active: false },
  { id: "rivos", name: "Rivos", type: "greenhouse", url: "https://rivos.com/careers", category: "fabless", batch: 3, active: false },
  { id: "tenstorrent", name: "Tenstorrent", type: "workday", url: "https://tenstorrent.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "axelera-ai", name: "Axelera AI", type: "greenhouse", url: "https://axelera.ai/careers/", category: "fabless", batch: 3, active: false },
  { id: "untether-ai", name: "Untether AI", type: "greenhouse", url: "https://untether.ai/careers/", category: "fabless", batch: 3, active: false },
  { id: "mythic-ai", name: "Mythic", type: "html", url: "https://mythic.ai/careers/", category: "fabless", batch: 3, active: false },
  { id: "hailo", name: "Hailo", type: "greenhouse", url: "https://hailo.ai/careers/", category: "fabless", batch: 3, active: false },
  { id: "edgecortix", name: "EdgeCortix", type: "html", url: "https://edgecortix.com/careers/", category: "fabless", batch: 3, active: false },
  { id: "ceva", name: "Ceva Inc", type: "html", url: "https://www.ceva-ip.com/about/careers/", category: "fabless", batch: 3, active: false },
  { id: "andes-tech", name: "Andes Technology", type: "html", url: "https://www.andestech.com/en/about/careers/", category: "fabless", batch: 3, active: false },
  { id: "innosilicon", name: "Innosilicon", type: "html", url: "https://www.innosilicon.com/en/careers/", category: "fabless", batch: 3, active: false },
  { id: "verisilicon", name: "VeriSilicon", type: "html", url: "https://www.verisilicon.com/en/Careers", category: "fabless", batch: 3, active: false },
  { id: "alphawave-semi", name: "Alphawave Semi", type: "greenhouse", url: "https://alphawavesemi.com/careers/", category: "fabless", batch: 3, active: false },
  { id: "astera-labs", name: "Astera Labs", type: "greenhouse", url: "https://asteralabs.com/careers/", category: "fabless", batch: 3, active: false },
  { id: "credo-tech", name: "Credo Technology", type: "workday", url: "https://credotech.wd1.myworkdayjobs.com/", category: "fabless", batch: 3, active: false },
  { id: "lam-research", name: "Lam Research", type: "workday", url: "https://lamresearch.wd1.myworkdayjobs.com/", category: "equipment", batch: 3, active: false },
  { id: "kla", name: "KLA Corporation", type: "workday", url: "https://kla.wd1.myworkdayjobs.com/", category: "equipment", batch: 3, active: false },
  { id: "tokyo-electron", name: "Tokyo Electron", type: "html", url: "https://www.tel.com/careers/", category: "equipment", batch: 3, active: false },
  { id: "advantest", name: "Advantest", type: "html", url: "https://www.advantest.com/careers", category: "equipment", batch: 3, active: false },
  { id: "teradyne", name: "Teradyne", type: "workday", url: "https://teradyne.wd1.myworkdayjobs.com/", category: "equipment", batch: 3, active: false },
  { id: "entegris", name: "Entegris", type: "workday", url: "https://entegris.wd1.myworkdayjobs.com/", category: "equipment", batch: 3, active: false },
  { id: "merck-ed", name: "Merck KGaA (EMD Electronics)", type: "workday", url: "https://merckgroup.wd3.myworkdayjobs.com/", category: "materials", batch: 3, active: false },
  { id: "shin-etsu", name: "Shin-Etsu Chemical", type: "html", url: "https://www.shinetsu.co.jp/en/careers/", category: "materials", batch: 3, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 4: More Materials + OSAT + Power + EDA + T&M  (~30, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "sumco", name: "SUMCO Corporation", type: "html", url: "https://www.sumcosi.com/english/recruit/", category: "materials", batch: 4, active: false },
  { id: "corning", name: "Corning Incorporated", type: "workday", url: "https://corning.wd1.myworkdayjobs.com/", category: "materials", batch: 4, active: false },
  { id: "dupont-electronics", name: "DuPont Electronics", type: "workday", url: "https://dupont.wd1.myworkdayjobs.com/", category: "materials", batch: 4, active: false },
  { id: "3m-electronics", name: "3M Electronics", type: "workday", url: "https://3m.wd1.myworkdayjobs.com/", category: "materials", batch: 4, active: false },
  { id: "basf-electronics", name: "BASF Electronic Materials", type: "workday", url: "https://basf.wd3.myworkdayjobs.com/", category: "materials", batch: 4, active: false },
  { id: "air-products", name: "Air Products", type: "workday", url: "https://airproducts.wd1.myworkdayjobs.com/", category: "materials", batch: 4, active: false },
  { id: "linde-electronics", name: "Linde Electronics", type: "workday", url: "https://linde.wd1.myworkdayjobs.com/", category: "materials", batch: 4, active: false },
  { id: "nikon-precision", name: "Nikon Precision", type: "html", url: "https://www.nikonprecision.com/careers/", category: "equipment", batch: 4, active: false },
  { id: "canon-semi", name: "Canon Semiconductor Equipment", type: "html", url: "https://www.canon.com/careers/", category: "equipment", batch: 4, active: false },
  { id: "screen-semi", name: "Screen Semiconductor Solutions", type: "html", url: "https://www.screen.co.jp/en/careers/", category: "equipment", batch: 4, active: false },
  { id: "hitachi-hightech", name: "Hitachi High-Tech", type: "html", url: "https://www.hitachi-hightech.com/global/en/careers/", category: "equipment", batch: 4, active: false },
  { id: "asm-intl", name: "ASM International", type: "workday", url: "https://asm.wd3.myworkdayjobs.com/", category: "equipment", batch: 4, active: false },
  { id: "axcelis", name: "Axcelis Technologies", type: "workday", url: "https://axcelis.wd1.myworkdayjobs.com/", category: "equipment", batch: 4, active: false },
  { id: "onto-innovation", name: "Onto Innovation", type: "workday", url: "https://ontoinnovation.wd1.myworkdayjobs.com/", category: "equipment", batch: 4, active: false },
  { id: "brooks-auto", name: "Brooks Automation", type: "html", url: "https://www.brooks.com/careers", category: "equipment", batch: 4, active: false },
  { id: "veeco", name: "Veeco Instruments", type: "workday", url: "https://veeco.wd1.myworkdayjobs.com/", category: "equipment", batch: 4, active: false },
  { id: "amkor", name: "Amkor Technology", type: "html", url: "https://amkor.com/careers/", category: "osat", batch: 4, active: false },
  { id: "ase", name: "ASE Technology Holding", type: "html", url: "https://www.aseglobal.com/en/careers", category: "osat", batch: 4, active: false },
  { id: "jcet", name: "JCET Group", type: "html", url: "https://www.jcetglobal.com/en/careers/", category: "osat", batch: 4, active: false },
  { id: "pti", name: "Powertech Technology", type: "html", url: "https://www.pti.com.tw/en/careers/", category: "osat", batch: 4, active: false },
  { id: "chipbond", name: "Chipbond Technology", type: "html", url: "https://www.chipbond.com.tw/en/careers/", category: "osat", batch: 4, active: false },
  { id: "kyec", name: "King Yuan Electronics", type: "html", url: "https://www.kyec.com.tw/en/careers/", category: "osat", batch: 4, active: false },
  { id: "spil", name: "Siliconware Precision Industries", type: "html", url: "https://www.spil.com.tw/en/careers/", category: "osat", batch: 4, active: false },
  { id: "chipmos", name: "ChipMOS Technologies", type: "html", url: "https://www.chipmos.com/en/careers/", category: "osat", batch: 4, active: false },
  { id: "utac", name: "UTAC Group", type: "html", url: "https://www.utacgroup.com/careers/", category: "osat", batch: 4, active: false },
  { id: "tongfu-micro", name: "Tongfu Microelectronics", type: "html", url: "https://www.tfme.com/en/careers/", category: "osat", batch: 4, active: false },
  { id: "allegro-micro", name: "Allegro MicroSystems", type: "workday", url: "https://allegromicro.wd1.myworkdayjobs.com/", category: "power-auto", batch: 4, active: false },
  { id: "melexis", name: "Melexis", type: "workday", url: "https://melexis.wd3.myworkdayjobs.com/", category: "power-auto", batch: 4, active: false },
  { id: "elmos", name: "Elmos Semiconductor", type: "html", url: "https://www.elmos.com/careers/", category: "power-auto", batch: 4, active: false },
  { id: "bosch-sensortec", name: "Bosch Sensortec", type: "workday", url: "https://bosch.wd3.myworkdayjobs.com/", category: "power-auto", batch: 4, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 5: Power Semi + EDA + T&M + National Labs  (~30, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "semtech", name: "Semtech", type: "workday", url: "https://semtech.wd1.myworkdayjobs.com/", category: "power-auto", batch: 5, active: false },
  { id: "power-integrations", name: "Power Integrations", type: "workday", url: "https://powerint.wd1.myworkdayjobs.com/", category: "power-auto", batch: 5, active: false },
  { id: "navitas", name: "Navitas Semiconductor", type: "greenhouse", url: "https://navitas.com/careers/", category: "power-auto", batch: 5, active: false },
  { id: "gan-systems", name: "GaN Systems", type: "html", url: "https://gansystems.com/careers/", category: "power-auto", batch: 5, active: false },
  { id: "epc-co", name: "EPC (Efficient Power Conversion)", type: "html", url: "https://epc-co.com/epc/careers", category: "power-auto", batch: 5, active: false },
  { id: "littelfuse", name: "Littelfuse", type: "workday", url: "https://littelfuse.wd1.myworkdayjobs.com/", category: "power-auto", batch: 5, active: false },
  { id: "ymtc", name: "YMTC (Yangtze Memory)", type: "html", url: "https://www.ymtc.com/en/careers/", category: "memory-storage", batch: 5, active: false },
  { id: "cxmt", name: "CXMT (ChangXin Memory)", type: "html", url: "https://www.cxmt.com/en/careers/", category: "memory-storage", batch: 5, active: false },
  { id: "innodisk", name: "Innodisk", type: "html", url: "https://www.innodisk.com/en/careers/", category: "memory-storage", batch: 5, active: false },
  { id: "netlist", name: "Netlist", type: "html", url: "https://www.netlist.com/careers/", category: "memory-storage", batch: 5, active: false },
  { id: "rambus", name: "Rambus", type: "workday", url: "https://rambus.wd1.myworkdayjobs.com/", category: "memory-storage", batch: 5, active: false },
  { id: "silicon-motion", name: "Silicon Motion Technology", type: "html", url: "https://www.siliconmotion.com/careers/", category: "memory-storage", batch: 5, active: false },
  { id: "keysight", name: "Keysight Technologies", type: "workday", url: "https://keysight.wd1.myworkdayjobs.com/", category: "test-measurement", batch: 5, active: false },
  { id: "rohde-schwarz", name: "Rohde & Schwarz", type: "workday", url: "https://rohdeschwarz.wd3.myworkdayjobs.com/", category: "test-measurement", batch: 5, active: false },
  { id: "anritsu", name: "Anritsu", type: "html", url: "https://www.anritsu.com/en-US/careers", category: "test-measurement", batch: 5, active: false },
  { id: "litepoint", name: "LitePoint", type: "html", url: "https://www.litepoint.com/about/careers/", category: "test-measurement", batch: 5, active: false },
  { id: "siemens-eda", name: "Siemens EDA", type: "workday", url: "https://siemens.wd1.myworkdayjobs.com/", category: "eda", batch: 5, active: false },
  { id: "ansys", name: "Ansys", type: "workday", url: "https://ansys.wd1.myworkdayjobs.com/", category: "eda", batch: 5, active: false },
  { id: "ni", name: "National Instruments", type: "workday", url: "https://ni.wd1.myworkdayjobs.com/", category: "eda", batch: 5, active: false },
  { id: "xpeedic", name: "Xpeedic", type: "html", url: "https://www.xpeedic.com/careers/", category: "eda", batch: 5, active: false },
  { id: "empyrean", name: "Empyrean Technology", type: "html", url: "https://www.empyrean.com.cn/en/careers/", category: "eda", batch: 5, active: false },
  { id: "zuken", name: "Zuken", type: "html", url: "https://www.zuken.com/en/careers/", category: "eda", batch: 5, active: false },
  { id: "silvaco", name: "Silvaco", type: "html", url: "https://silvaco.com/careers/", category: "eda", batch: 5, active: false },
  { id: "innovium", name: "Innovium (Cisco)", type: "workday", url: "https://cisco.wd1.myworkdayjobs.com/", category: "networking-chip", batch: 5, active: false },
  { id: "ciena", name: "Ciena", type: "workday", url: "https://ciena.wd1.myworkdayjobs.com/", category: "networking-chip", batch: 5, active: false },
  { id: "cisco-silicon", name: "Cisco Silicon One", type: "workday", url: "https://cisco.wd1.myworkdayjobs.com/", category: "networking-chip", batch: 5, active: false },
  { id: "xsight-labs", name: "Xsight Labs", type: "html", url: "https://xsightlabs.com/careers/", category: "networking-chip", batch: 5, active: false },
  { id: "dmatrix", name: "d-Matrix", type: "greenhouse", url: "https://d-matrix.ai/careers/", category: "fabless", batch: 5, active: false },
  { id: "blaize", name: "Blaize", type: "greenhouse", url: "https://blaize.com/careers/", category: "fabless", batch: 5, active: false },
  { id: "db-hitek", name: "DB HiTek", type: "html", url: "https://www.dbhitek.com/en/careers/", category: "semiconductor-idm", batch: 5, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 6: National Labs India + International  (~30, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "lrde", name: "DRDO LRDE", type: "html", url: "https://www.drdo.gov.in/labs-and-establishments/lrde", category: "national-lab-india", batch: 6, active: false },
  { id: "deal", name: "DRDO DEAL", type: "html", url: "https://www.drdo.gov.in/labs-and-establishments/deal", category: "national-lab-india", batch: 6, active: false },
  { id: "rci", name: "DRDO RCI", type: "html", url: "https://www.drdo.gov.in/labs-and-establishments/rci", category: "national-lab-india", batch: 6, active: false },
  { id: "sag-drdo", name: "DRDO SAG", type: "html", url: "https://www.drdo.gov.in/labs-and-establishments/sag", category: "national-lab-india", batch: 6, active: false },
  { id: "cair", name: "DRDO CAIR", type: "html", url: "https://www.drdo.gov.in/labs-and-establishments/cair", category: "national-lab-india", batch: 6, active: false },
  { id: "ceeri", name: "CSIR CEERI", type: "html", url: "https://www.ceeri.res.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "npl", name: "CSIR NPL", type: "html", url: "https://www.nplindia.org/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "csio", name: "CSIR CSIO", type: "html", url: "https://www.csio.res.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "cmeri", name: "CSIR CMERI", type: "html", url: "https://www.cmeri.res.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "cdot", name: "C-DOT", type: "html", url: "https://wwwcdot.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "cmet", name: "C-MET", type: "html", url: "https://www.cmet.gov.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "vssc", name: "VSSC", type: "html", url: "https://www.vssc.gov.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "sac", name: "SAC (Space Applications Centre)", type: "html", url: "https://www.sac.gov.in/careers/", category: "national-lab-india", batch: 6, active: false },
  { id: "fraunhofer-iis", name: "Fraunhofer IIS", type: "html", url: "https://www.iis.fraunhofer.de/en/careers.html", category: "national-lab-intl", batch: 6, active: false },
  { id: "fraunhofer-ipms", name: "Fraunhofer IPMS", type: "html", url: "https://www.ipms.fraunhofer.de/en/careers.html", category: "national-lab-intl", batch: 6, active: false },
  { id: "fraunhofer-enas", name: "Fraunhofer ENAS", type: "html", url: "https://www.enas.fraunhofer.de/en/careers.html", category: "national-lab-intl", batch: 6, active: false },
  { id: "astar-ime", name: "A*STAR IME", type: "html", url: "https://www.a-star.edu.sg/ime/careers", category: "national-lab-intl", batch: 6, active: false },
  { id: "astar-imre", name: "A*STAR IMRE", type: "html", url: "https://www.a-star.edu.sg/imre/careers", category: "national-lab-intl", batch: 6, active: false },
  { id: "nist", name: "NIST (USA)", type: "workday", url: "https://nist.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },
  { id: "sandia", name: "Sandia National Laboratories", type: "workday", url: "https://sandia.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },
  { id: "argonne", name: "Argonne National Laboratory", type: "workday", url: "https://anl.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },
  { id: "ornl", name: "Oak Ridge National Laboratory", type: "workday", url: "https://ornl.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },
  { id: "lbl", name: "Lawrence Berkeley National Lab", type: "workday", url: "https://lbl.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },
  { id: "riken", name: "RIKEN", type: "html", url: "https://www.riken.jp/en/careers/", category: "national-lab-intl", batch: 6, active: false },
  { id: "itri", name: "ITRI (Taiwan)", type: "html", url: "https://www.itri.org.tw/eng/careers/", category: "national-lab-intl", batch: 6, active: false },
  { id: "etri", name: "ETRI (South Korea)", type: "html", url: "https://www.etri.re.kr/eng/recruit/", category: "national-lab-intl", batch: 6, active: false },
  { id: "vtt", name: "VTT Technical Research Centre", type: "html", url: "https://www.vttresearch.com/en/careers", category: "national-lab-intl", batch: 6, active: false },
  { id: "cnrs", name: "CNRS (France)", type: "html", url: "https://www.cnrs.fr/en/careers", category: "national-lab-intl", batch: 6, active: false },
  { id: "csiro", name: "CSIRO (Australia)", type: "workday", url: "https://csiro.wd1.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },
  { id: "tno", name: "TNO (Netherlands)", type: "workday", url: "https://tno.wd3.myworkdayjobs.com/", category: "national-lab-intl", batch: 6, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 7: More Intl Labs + India Universities  (~30, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "max-planck", name: "Max Planck Institutes", type: "html", url: "https://www.mpg.de/careers", category: "national-lab-intl", batch: 7, active: false },
  { id: "kacst", name: "KACST (Saudi Arabia)", type: "html", url: "https://www.kacst.edu.sa/careers/", category: "national-lab-intl", batch: 7, active: false },
  { id: "kist", name: "KIST (South Korea)", type: "html", url: "https://www.kist.re.kr/en/recruit/", category: "national-lab-intl", batch: 7, active: false },
  { id: "iit-madras", name: "IIT Madras", type: "html", url: "https://www.iitm.ac.in/careers", category: "university-india", batch: 7, active: false },
  { id: "iit-kanpur", name: "IIT Kanpur", type: "html", url: "https://www.iitk.ac.in/careers", category: "university-india", batch: 7, active: false },
  { id: "iit-kharagpur", name: "IIT Kharagpur", type: "html", url: "https://www.iitkgp.ac.in/careers", category: "university-india", batch: 7, active: false },
  { id: "iit-roorkee", name: "IIT Roorkee", type: "html", url: "https://www.iitr.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-guwahati", name: "IIT Guwahati", type: "html", url: "https://www.iitg.ac.in/careers", category: "university-india", batch: 7, active: false },
  { id: "iit-hyderabad", name: "IIT Hyderabad", type: "html", url: "https://www.iith.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-bhu", name: "IIT BHU Varanasi", type: "html", url: "https://www.iitbhu.ac.in/careers", category: "university-india", batch: 7, active: false },
  { id: "iit-ism", name: "IIT ISM Dhanbad", type: "html", url: "https://www.iitism.ac.in/careers", category: "university-india", batch: 7, active: false },
  { id: "iit-indore", name: "IIT Indore", type: "html", url: "https://www.iiti.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-ropar", name: "IIT Ropar", type: "html", url: "https://www.iitrpr.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-gandhinagar", name: "IIT Gandhinagar", type: "html", url: "https://www.iitgn.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-patna", name: "IIT Patna", type: "html", url: "https://www.iitp.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-bhubaneswar", name: "IIT Bhubaneswar", type: "html", url: "https://www.iitbbs.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-mandi", name: "IIT Mandi", type: "html", url: "https://www.iitmandi.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-jodhpur", name: "IIT Jodhpur", type: "html", url: "https://www.iitj.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-palakkad", name: "IIT Palakkad", type: "html", url: "https://www.iitpkd.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-tirupati", name: "IIT Tirupati", type: "html", url: "https://www.iittp.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-dharwad", name: "IIT Dharwad", type: "html", url: "https://www.iitdh.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-bhilai", name: "IIT Bhilai", type: "html", url: "https://www.iitbhilai.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-goa", name: "IIT Goa", type: "html", url: "https://www.iitgoa.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "iit-jammu", name: "IIT Jammu", type: "html", url: "https://www.iitjammu.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "nit-trichy", name: "NIT Tiruchirappalli", type: "html", url: "https://www.nitt.edu/careers", category: "university-india", batch: 7, active: false },
  { id: "nit-warangal", name: "NIT Warangal", type: "html", url: "https://www.nitw.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "nit-surathkal", name: "NIT Surathkal", type: "html", url: "https://www.nitk.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "nit-rourkela", name: "NIT Rourkela", type: "html", url: "https://www.nitrkl.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "nit-calicut", name: "NIT Calicut", type: "html", url: "https://www.nitc.ac.in/careers/", category: "university-india", batch: 7, active: false },
  { id: "nit-durgapur", name: "NIT Durgapur", type: "html", url: "https://www.nitdgp.ac.in/careers/", category: "university-india", batch: 7, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 8: More India Universities + North America  (~35, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "nit-jalandhar", name: "NIT Jalandhar", type: "html", url: "https://www.nitj.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "nit-kurukshetra", name: "NIT Kurukshetra", type: "html", url: "https://www.nitkkr.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "mnnit", name: "MNNIT Allahabad", type: "html", url: "https://www.mnnit.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "manit", name: "MANIT Bhopal", type: "html", url: "https://www.manit.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "nit-nagpur", name: "VNIT Nagpur", type: "html", url: "https://www.vnit.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "nit-silchar", name: "NIT Silchar", type: "html", url: "https://www.nits.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiit-hyderabad", name: "IIIT Hyderabad", type: "html", url: "https://www.iiit.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiit-bangalore", name: "IIIT Bangalore", type: "html", url: "https://www.iiitb.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiit-delhi", name: "IIIT Delhi", type: "html", url: "https://www.iiitd.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiit-kancheepuram", name: "IIIT Kancheepuram", type: "html", url: "https://www.iiitk.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiser-pune", name: "IISER Pune", type: "html", url: "https://www.iiserpune.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiser-kolkata", name: "IISER Kolkata", type: "html", url: "https://www.iiserkol.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiser-bhopal", name: "IISER Bhopal", type: "html", url: "https://www.iiserb.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "iiser-mohali", name: "IISER Mohali", type: "html", url: "https://www.iisermohali.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "tifr", name: "TIFR", type: "html", url: "https://www.tifr.res.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "daiict", name: "DA-IICT", type: "html", url: "https://www.daiict.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "vit-vellore", name: "VIT Vellore", type: "html", url: "https://www.vit.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "srm", name: "SRM Institute", type: "html", url: "https://www.srmist.edu.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "manipal", name: "Manipal Institute of Technology", type: "html", url: "https://manipal.edu/mit/careers.html", category: "university-india", batch: 8, active: false },
  { id: "thapar", name: "Thapar Institute", type: "html", url: "https://www.thapar.edu/careers/", category: "university-india", batch: 8, active: false },
  { id: "pec", name: "PEC Chandigarh", type: "html", url: "https://www.pec.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "du-electronics", name: "Delhi University (Electronics)", type: "html", url: "https://www.du.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "jmi", name: "Jamia Millia Islamia", type: "html", url: "https://www.jmi.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "amu", name: "Aligarh Muslim University", type: "html", url: "https://www.amu.ac.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "jadavpur", name: "Jadavpur University", type: "html", url: "https://www.jaduniv.edu.in/careers/", category: "university-india", batch: 8, active: false },
  { id: "anna-univ", name: "Anna University", type: "html", url: "https://www.annauniv.edu/careers/", category: "university-india", batch: 8, active: false },
  { id: "mit-usa", name: "MIT", type: "workday", url: "https://mit.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "stanford", name: "Stanford", type: "workday", url: "https://stanford.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "uc-berkeley", name: "UC Berkeley", type: "workday", url: "https://ucberkeley.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "caltech", name: "Caltech", type: "workday", url: "https://caltech.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "gatech", name: "Georgia Tech", type: "workday", url: "https://gatech.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "uiuc", name: "UIUC", type: "workday", url: "https://illinois.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "purdue", name: "Purdue", type: "workday", url: "https://purdue.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "cornell", name: "Cornell", type: "workday", url: "https://cornell.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "umich", name: "University of Michigan", type: "workday", url: "https://umich.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },
  { id: "ut-austin", name: "UT Austin", type: "workday", url: "https://utexas.wd1.myworkdayjobs.com/", category: "university-na", batch: 8, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 9: More North America + Europe Universities  (~38, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "ucla", name: "UCLA", type: "workday", url: "https://ucla.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "uc-san-diego", name: "UC San Diego", type: "workday", url: "https://ucsd.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "cmu", name: "Carnegie Mellon", type: "workday", url: "https://cmu.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "umn", name: "University of Minnesota", type: "workday", url: "https://umn.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "asu", name: "Arizona State", type: "workday", url: "https://asu.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "rpi", name: "RPI", type: "workday", url: "https://rpi.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "penn-state", name: "Penn State", type: "workday", url: "https://psu.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "uw", name: "University of Washington", type: "workday", url: "https://uw.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "uw-madison", name: "UW Madison", type: "workday", url: "https://wisc.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "ut-dallas", name: "UT Dallas", type: "workday", url: "https://utdallas.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "columbia", name: "Columbia University", type: "workday", url: "https://columbia.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "princeton", name: "Princeton", type: "workday", url: "https://princeton.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "upenn", name: "University of Pennsylvania", type: "workday", url: "https://upenn.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "northwestern", name: "Northwestern", type: "workday", url: "https://northwestern.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "ohio-state", name: "Ohio State", type: "workday", url: "https://osu.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "umd", name: "University of Maryland", type: "workday", url: "https://umd.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "vt", name: "Virginia Tech", type: "workday", url: "https://vt.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "nc-state", name: "NC State", type: "workday", url: "https://ncsu.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "ucsb", name: "UC Santa Barbara", type: "workday", url: "https://ucsb.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "cu-boulder", name: "UC Boulder", type: "workday", url: "https://colorado.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "notre-dame", name: "University of Notre Dame", type: "workday", url: "https://nd.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "uoft", name: "University of Toronto", type: "workday", url: "https://utoronto.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "mcgill", name: "McGill", type: "workday", url: "https://mcgill.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "uwaterloo", name: "University of Waterloo", type: "workday", url: "https://uwaterloo.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "ubc", name: "University of British Columbia", type: "workday", url: "https://ubc.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "ualberta", name: "University of Alberta", type: "workday", url: "https://ualberta.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "concordia", name: "Concordia University", type: "workday", url: "https://concordia.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "sfu", name: "Simon Fraser University", type: "workday", url: "https://sfu.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "uottawa", name: "University of Ottawa", type: "workday", url: "https://uottawa.wd1.myworkdayjobs.com/", category: "university-na", batch: 9, active: false },
  { id: "eth-zurich", name: "ETH Zurich", type: "html", url: "https://www.ethz.ch/en/jobs.html", category: "university-europe", batch: 9, active: false },
  { id: "epfl", name: "EPFL", type: "html", url: "https://www.epfl.ch/about/working/", category: "university-europe", batch: 9, active: false },
  { id: "tu-delft", name: "TU Delft", type: "html", url: "https://www.tudelft.nl/over-tu-delft/werken-bij/", category: "university-europe", batch: 9, active: false },
  { id: "tu-eindhoven", name: "TU Eindhoven", type: "html", url: "https://www.tue.nl/en/working-at-tue/", category: "university-europe", batch: 9, active: false },
  { id: "utwente", name: "University of Twente", type: "html", url: "https://www.utwente.nl/en/jobs/", category: "university-europe", batch: 9, active: false },
  { id: "tum", name: "TU Munich", type: "html", url: "https://www.tum.de/en/about-tum/working-at-tum/", category: "university-europe", batch: 9, active: false },
  { id: "rwth-aachen", name: "RWTH Aachen", type: "html", url: "https://www.rwth-aachen.de/jobs", category: "university-europe", batch: 9, active: false },
  { id: "tu-berlin", name: "TU Berlin", type: "html", url: "https://www.tu.berlin/en/working/", category: "university-europe", batch: 9, active: false },
  { id: "kit", name: "KIT Karlsruhe", type: "html", url: "https://www.kit.edu/kit/karriere.php", category: "university-europe", batch: 9, active: false },
  { id: "ku-leuven", name: "KU Leuven", type: "html", url: "https://www.kuleuven.be/jobs/", category: "university-europe", batch: 9, active: false },
  { id: "ghent", name: "Ghent University", type: "html", url: "https://www.ugent.be/en/jobs", category: "university-europe", batch: 9, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 10: More Europe + Asia-Pacific Universities  (~35, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "imperial", name: "Imperial College London", type: "workday", url: "https://imperial.wd1.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "cambridge", name: "University of Cambridge", type: "workday", url: "https://cam.wd1.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "oxford", name: "University of Oxford", type: "workday", url: "https://oxford.wd1.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "manchester", name: "University of Manchester", type: "workday", url: "https://manchester.wd3.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "southampton", name: "University of Southampton", type: "workday", url: "https://southampton.wd3.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "ucl", name: "University College London", type: "workday", url: "https://ucl.wd1.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "edinburgh", name: "University of Edinburgh", type: "workday", url: "https://edinburgh.wd3.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "bristol", name: "University of Bristol", type: "workday", url: "https://bristol.wd3.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "kth", name: "KTH Royal Institute of Technology", type: "html", url: "https://www.kth.se/en/om/work-at-kth", category: "university-europe", batch: 10, active: false },
  { id: "chalmers", name: "Chalmers University", type: "html", url: "https://www.chalmers.se/en/about-chalmers/working-at-chalmers/", category: "university-europe", batch: 10, active: false },
  { id: "uppsala", name: "Uppsala University", type: "html", url: "https://www.uu.se/en/about-uu/join-us/", category: "university-europe", batch: 10, active: false },
  { id: "polimi", name: "Politecnico di Milano", type: "html", url: "https://www.polimi.it/en/current-job-openings/", category: "university-europe", batch: 10, active: false },
  { id: "polito", name: "Politecnico di Torino", type: "html", url: "https://www.polito.it/en/jobs", category: "university-europe", batch: 10, active: false },
  { id: "unibo", name: "University of Bologna", type: "html", url: "https://www.unibo.it/en/about-us/working-at-unibo", category: "university-europe", batch: 10, active: false },
  { id: "sapienza", name: "Sapienza University of Rome", type: "html", url: "https://www.uniroma1.it/it/lavoro", category: "university-europe", batch: 10, active: false },
  { id: "uga", name: "University Grenoble Alpes", type: "html", url: "https://www.univ-grenoble-alpes.fr/en/jobs/", category: "university-europe", batch: 10, active: false },
  { id: "sorbonne", name: "Sorbonne University", type: "html", url: "https://www.sorbonne-universite.fr/en/jobs", category: "university-europe", batch: 10, active: false },
  { id: "dtu", name: "Technical University of Denmark", type: "html", url: "https://www.dtu.dk/english/about/job-and-career", category: "university-europe", batch: 10, active: false },
  { id: "aalto", name: "Aalto University", type: "html", url: "https://www.aalto.fi/en/careers", category: "university-europe", batch: 10, active: false },
  { id: "aalborg", name: "Aalborg University", type: "html", url: "https://www.en.aau.dk/about-aau/job/", category: "university-europe", batch: 10, active: false },
  { id: "ntnu", name: "NTNU", type: "html", url: "https://www.ntnu.edu/jobs", category: "university-europe", batch: 10, active: false },
  { id: "tcd", name: "Trinity College Dublin", type: "html", url: "https://www.tcd.ie/hr/vacancies/", category: "university-europe", batch: 10, active: false },
  { id: "ucd", name: "University College Dublin", type: "workday", url: "https://ucd.wd1.myworkdayjobs.com/", category: "university-europe", batch: 10, active: false },
  { id: "tu-wien", name: "TU Vienna", type: "html", url: "https://www.tuwien.at/en/working/", category: "university-europe", batch: 10, active: false },
  { id: "stuttgart", name: "University of Stuttgart", type: "html", url: "https://www.uni-stuttgart.de/en/jobs/", category: "university-europe", batch: 10, active: false },
  { id: "pw", name: "Warsaw University of Technology", type: "html", url: "https://www.pw.edu.pl/eng/Jobs", category: "university-europe", batch: 10, active: false },
  { id: "lund", name: "Lund University", type: "html", url: "https://www.lunduniversity.lu.se/about-university/work-lund-university", category: "university-europe", batch: 10, active: false },
  { id: "nus", name: "National University of Singapore", type: "workday", url: "https://nus.wd1.myworkdayjobs.com/", category: "university-apac", batch: 10, active: false },
  { id: "ntu-sg", name: "NTU Singapore", type: "workday", url: "https://ntu.wd1.myworkdayjobs.com/", category: "university-apac", batch: 10, active: false },
  { id: "tsinghua", name: "Tsinghua University", type: "html", url: "https://www.tsinghua.edu.cn/en/jobs/", category: "university-apac", batch: 10, active: false },
  { id: "pku", name: "Peking University", type: "html", url: "https://www.pku.edu.cn/en/careers/", category: "university-apac", batch: 10, active: false },
  { id: "fudan", name: "Fudan University", type: "html", url: "https://www.fudan.edu.cn/en/careers/", category: "university-apac", batch: 10, active: false },
  { id: "sjtu", name: "Shanghai Jiao Tong", type: "html", url: "https://www.sjtu.edu.cn/en/careers/", category: "university-apac", batch: 10, active: false },
  { id: "zju", name: "Zhejiang University", type: "html", url: "https://www.zju.edu.cn/english/careers/", category: "university-apac", batch: 10, active: false },
  { id: "ustc", name: "USTC", type: "html", url: "https://en.ustc.edu.cn/careers/", category: "university-apac", batch: 10, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 11: More APAC + Middle East + Latin America + Africa  (~30, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "xjtu", name: "Xi'an Jiaotong University", type: "html", url: "https://www.xjtu.edu.cn/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "hust", name: "Huazhong University of Science & Tech", type: "html", url: "https://english.hust.edu.cn/careers/", category: "university-apac", batch: 11, active: false },
  { id: "seu", name: "Southeast University", type: "html", url: "https://www.seu.edu.cn/english/careers/", category: "university-apac", batch: 11, active: false },
  { id: "buaa", name: "Beihang University", type: "html", url: "https://www.buaa.edu.cn/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "hit", name: "Harbin Institute of Technology", type: "html", url: "https://www.hit.edu.cn/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "kaist", name: "KAIST", type: "html", url: "https://www.kaist.ac.kr/en/html/recruit/", category: "university-apac", batch: 11, active: false },
  { id: "snu", name: "Seoul National University", type: "html", url: "https://en.snu.ac.kr/careers/", category: "university-apac", batch: 11, active: false },
  { id: "yonsei", name: "Yonsei University", type: "html", url: "https://www.yonsei.ac.kr/en_sc/careers.jsp", category: "university-apac", batch: 11, active: false },
  { id: "postech", name: "POSTECH", type: "html", url: "https://www.postech.ac.kr/eng/careers/", category: "university-apac", batch: 11, active: false },
  { id: "skku", name: "SKKU", type: "html", url: "https://www.skku.edu/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "hanyang", name: "Hanyang University", type: "html", url: "https://www.hanyang.ac.kr/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "korea-univ", name: "Korea University", type: "html", url: "https://www.korea.edu/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "utokyo", name: "University of Tokyo", type: "html", url: "https://www.u-tokyo.ac.jp/en/about/jobs.html", category: "university-apac", batch: 11, active: false },
  { id: "tokyo-tech", name: "Tokyo Institute of Technology", type: "html", url: "https://www.titech.ac.jp/english/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "osaka-u", name: "Osaka University", type: "html", url: "https://www.osaka-u.ac.jp/en/employment/", category: "university-apac", batch: 11, active: false },
  { id: "kyoto-u", name: "Kyoto University", type: "html", url: "https://www.kyoto-u.ac.jp/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "tohoku", name: "Tohoku University", type: "html", url: "https://www.tohoku.ac.jp/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "nagoya-u", name: "Nagoya University", type: "html", url: "https://www.nagoya-u.ac.jp/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "waseda", name: "Waseda University", type: "html", url: "https://www.waseda.jp/top/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "keio", name: "Keio University", type: "html", url: "https://www.keio.ac.jp/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "ntu-tw", name: "National Taiwan University", type: "html", url: "https://www.ntu.edu.tw/english/careers/", category: "university-apac", batch: 11, active: false },
  { id: "nctu", name: "NYCU (Taiwan)", type: "html", url: "https://www.nycu.edu.tw/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "nthu", name: "National Tsing Hua University", type: "html", url: "https://www.nthu.edu.tw/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "ncku", name: "National Cheng Kung University", type: "html", url: "https://www.ncku.edu.tw/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "hkust", name: "HKUST", type: "workday", url: "https://hkust.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "cuhk", name: "CUHK", type: "workday", url: "https://cuhk.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "hku", name: "University of Hong Kong", type: "workday", url: "https://hku.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "sydney", name: "University of Sydney", type: "workday", url: "https://sydney.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "unsw", name: "UNSW Sydney", type: "workday", url: "https://unsw.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "melbourne", name: "University of Melbourne", type: "workday", url: "https://unimelb.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "anu", name: "Australian National University", type: "workday", url: "https://anu.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "monash", name: "Monash University", type: "workday", url: "https://monash.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "auckland", name: "University of Auckland", type: "workday", url: "https://auckland.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "qut", name: "Queensland University of Technology", type: "workday", url: "https://qut.wd1.myworkdayjobs.com/", category: "university-apac", batch: 11, active: false },
  { id: "technion", name: "Technion", type: "html", url: "https://www.technion.ac.il/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "tau", name: "Tel Aviv University", type: "html", url: "https://www.tau.ac.il/en/jobs/", category: "university-apac", batch: 11, active: false },
  { id: "bgu", name: "Ben-Gurion University", type: "html", url: "https://in.bgu.ac.il/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "huji", name: "Hebrew University of Jerusalem", type: "html", url: "https://www.huji.ac.il/en/careers/", category: "university-apac", batch: 11, active: false },
  { id: "weizmann", name: "Weizmann Institute", type: "html", url: "https://www.weizmann.ac.il/feeds/careers/", category: "university-apac", batch: 11, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 12: Middle East + Latin America + Africa  (~10, inactive)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "kaust", name: "KAUST", type: "workday", url: "https://kaust.wd1.myworkdayjobs.com/", category: "university-me", batch: 12, active: false },
  { id: "khalifa", name: "Khalifa University", type: "html", url: "https://www.ku.ac.ae/careers/", category: "university-me", batch: 12, active: false },
  { id: "kfupm", name: "King Fahd University of Petroleum", type: "html", url: "https://www.kfupm.edu.sa/en/careers/", category: "university-me", batch: 12, active: false },
  { id: "aub", name: "American University of Beirut", type: "workday", url: "https://aub.wd1.myworkdayjobs.com/", category: "university-me", batch: 12, active: false },
  { id: "usp", name: "University of São Paulo", type: "html", url: "https://www5.usp.br/en/jobs/", category: "university-latam", batch: 12, active: false },
  { id: "unicamp", name: "UNICAMP", type: "html", url: "https://www.unicamp.br/unicamp/careers/", category: "university-latam", batch: 12, active: false },
  { id: "tec-mty", name: "Tecnológico de Monterrey", type: "workday", url: "https://tec.mx/en/careers", category: "university-latam", batch: 12, active: false },
  { id: "puc-chile", name: "Pontificia Universidad Católica de Chile", type: "html", url: "https://www.uc.cl/en/careers/", category: "university-latam", batch: 12, active: false },
  { id: "uct", name: "University of Cape Town", type: "workday", url: "https://uct.wd1.myworkdayjobs.com/", category: "university-africa", batch: 12, active: false },
  { id: "wits", name: "University of the Witwatersrand", type: "html", url: "https://www.wits.ac.za/careers/", category: "university-africa", batch: 12, active: false },

  // ═══════════════════════════════════════════════════════════════════════════
  // Batch 13: RSS News + Opportunity Feeds  (~10, inactive until verified)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "academic-positions", name: "Academic Positions RSS", type: "rss", url: "https://www.academicpositions.com/feeds/rss", category: "opportunity-rss", batch: 13, active: false },
  { id: "scholarship-roof", name: "Scholarship Roof RSS", type: "rss", url: "https://www.scholarshiproof.com/feed/", category: "opportunity-rss", batch: 13, active: false },
  { id: "jobs-ac-uk", name: "Jobs.ac.uk RSS", type: "rss", url: "https://www.jobs.ac.uk/jobs/rss", category: "opportunity-rss", batch: 13, active: false },
  { id: "ieee-spectrum", name: "IEEE Spectrum RSS", type: "rss", url: "https://spectrum.ieee.org/feeds/rss", category: "news-rss", batch: 13, active: false },
  { id: "ee-times", name: "EE Times RSS", type: "rss", url: "https://www.eetimes.com/feed/", category: "news-rss", batch: 13, active: false },
  { id: "electronics-weekly", name: "Electronics Weekly RSS", type: "rss", url: "https://www.electronicsweekly.com/feed/", category: "news-rss", batch: 13, active: false },
  { id: "e-foryou", name: "Electronics For You RSS", type: "rss", url: "https://www.electronicsforu.com/feed", category: "news-rss", batch: 13, active: false },
  { id: "nature-electronics", name: "Nature Electronics RSS", type: "rss", url: "https://www.nature.com/natelectron/feed.rss", category: "news-rss", batch: 13, active: false },
  { id: "india-semi-mission", name: "India Semiconductor Mission RSS", type: "rss", url: "https://ism.gov.in/feed/", category: "news-rss", batch: 13, active: false },
  { id: "iesanews", name: "IESA RSS", type: "rss", url: "https://iesaonline.org/feed/", category: "news-rss", batch: 13, active: false },
];

export function getSourcesForBatch(batch: number | "all"): SourceConfig[] {
  if (batch === "all") return SOURCES.filter((s) => s.active);
  return SOURCES.filter((s) => s.batch === batch && s.active);
}

export function getSourceById(id: string): SourceConfig | undefined {
  return SOURCES.find((s) => s.id === id);
}
