apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berojgardegreewala-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - berojgardegreewala.com
        - www.berojgardegreewala.com
      secretName: berojgardegreewala-tls
  rules:
    - host: berojgardegreewala.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berojgardegreewala-service
                port:
                  number: 80
